module FinchAPI
  module Resources
    class Jobs
      class Automated
        def create: (
          type: FinchAPI::Models::Jobs::AutomatedCreateParams::type_,
          params: FinchAPI::Models::Jobs::AutomatedCreateParams::Params,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Jobs::AutomatedCreateResponse

        def retrieve: (
          String job_id,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Jobs::AutomatedAsyncJob

        def list: (
          ?limit: Integer,
          ?offset: Integer,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Jobs::AutomatedListResponse

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
