module FinchAPI
  module Resources
    class Sandbox
      class Connections
        class Accounts
          def create: (
            company_id: String,
            provider_id: String,
            ?authentication_type: FinchAPI::Models::Sandbox::Connections::AccountCreateParams::authentication_type,
            ?products: ::Array[String],
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::Sandbox::Connections::AccountCreateResponse

          def update: (
            ?connection_status: FinchAPI::Models::connection_status_type,
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::Sandbox::Connections::AccountUpdateResponse

          def initialize: (client: FinchAPI::Client) -> void
        end
      end
    end
  end
end
