module FinchAPI
  module Models
    module Sandbox
      module Jobs
        type configuration_retrieve_params =
          {  } & FinchAPI::Internal::Type::request_parameters

        class ConfigurationRetrieveParams < FinchAPI::Internal::Type::BaseModel
          extend FinchAPI::Internal::Type::RequestParameters::Converter
          include FinchAPI::Internal::Type::RequestParameters

          def initialize: (?request_options: FinchAPI::request_opts) -> void

          def to_hash: -> FinchAPI::Models::Sandbox::Jobs::configuration_retrieve_params
        end
      end
    end
  end
end
