module FinchAPI
  module Models
    module Sandbox
      module Jobs
        type configuration_retrieve_response =
          ::Array[FinchAPI::Models::Sandbox::Jobs::SandboxJobConfiguration]

        ConfigurationRetrieveResponse: FinchAPI::Internal::Type::Converter
      end
    end
  end
end
