module FinchAPI
  module Models
    module Jobs
      type automated_create_params =
        {
          type: FinchAPI::Models::Jobs::AutomatedCreateParams::type_,
          params: FinchAPI::Jobs::AutomatedCreateParams::Params
        }
        & FinchAPI::Internal::Type::request_parameters

      class AutomatedCreateParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor type: FinchAPI::Models::Jobs::AutomatedCreateParams::type_

        attr_accessor params: FinchAPI::Jobs::AutomatedCreateParams::Params

        def initialize: (
          type: FinchAPI::Models::Jobs::AutomatedCreateParams::type_,
          params: FinchAPI::Jobs::AutomatedCreateParams::Params,
          ?request_options: FinchAPI::request_opts
        ) -> void

        type type_ = :w4_form_employee_sync

        module Type
          extend FinchAPI::Internal::Type::Enum

          W4_FORM_EMPLOYEE_SYNC: :w4_form_employee_sync

          def self?.values: -> ::Array[FinchAPI::Models::Jobs::AutomatedCreateParams::type_]
        end

        type params = { individual_id: String }

        class Params < FinchAPI::Internal::Type::BaseModel
          attr_accessor individual_id: String

          def initialize: (individual_id: String) -> void
        end
      end
    end
  end
end
