module FinchAPI
  module Models
    module Jobs
      type automated_create_response =
        {
          allowed_refreshes: Integer,
          job_id: String,
          job_url: String,
          remaining_refreshes: Integer
        }

      class AutomatedCreateResponse < FinchAPI::Internal::Type::BaseModel
        attr_accessor allowed_refreshes: Integer

        attr_accessor job_id: String

        attr_accessor job_url: String

        attr_accessor remaining_refreshes: Integer

        def initialize: (
          allowed_refreshes: Integer,
          job_id: String,
          job_url: String,
          remaining_refreshes: Integer
        ) -> void

        def to_hash: -> FinchAPI::Models::Jobs::automated_create_response
      end
    end
  end
end
