module FinchAPI
  module Models
    module Jobs
      type automated_create_params =
        { body: FinchAPI::Models::Jobs::AutomatedCreateParams::body }
        & FinchAPI::Internal::Type::request_parameters

      class AutomatedCreateParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor body: FinchAPI::Models::Jobs::AutomatedCreateParams::body

        def initialize: (
          body: FinchAPI::Models::Jobs::AutomatedCreateParams::body,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          body: FinchAPI::Models::Jobs::AutomatedCreateParams::body,
          request_options: FinchAPI::RequestOptions
        }

        type body =
          FinchAPI::Jobs::AutomatedCreateParams::Body::DataSyncAll
          | FinchAPI::Jobs::AutomatedCreateParams::Body::W4FormEmployeeSync

        module Body
          extend FinchAPI::Internal::Type::Union

          type data_sync_all = { type: :data_sync_all }

          class DataSyncAll < FinchAPI::Internal::Type::BaseModel
            attr_accessor type: :data_sync_all

            def initialize: (?type: :data_sync_all) -> void

            def to_hash: -> { type: :data_sync_all }
          end

          type w4_form_employee_sync =
            {
              params: FinchAPI::Jobs::AutomatedCreateParams::Body::W4FormEmployeeSync::Params,
              type: :w4_form_employee_sync
            }

          class W4FormEmployeeSync < FinchAPI::Internal::Type::BaseModel
            attr_accessor params: FinchAPI::Jobs::AutomatedCreateParams::Body::W4FormEmployeeSync::Params

            attr_accessor type: :w4_form_employee_sync

            def initialize: (
              params: FinchAPI::Jobs::AutomatedCreateParams::Body::W4FormEmployeeSync::Params,
              ?type: :w4_form_employee_sync
            ) -> void

            def to_hash: -> {
              params: FinchAPI::Jobs::AutomatedCreateParams::Body::W4FormEmployeeSync::Params,
              type: :w4_form_employee_sync
            }

            type params = { individual_id: String }

            class Params < FinchAPI::Internal::Type::BaseModel
              attr_accessor individual_id: String

              def initialize: (individual_id: String) -> void

              def to_hash: -> { individual_id: String }
            end
          end

          def self?.variants: -> ::Array[FinchAPI::Models::Jobs::AutomatedCreateParams::body]
        end
      end
    end
  end
end
