module FinchAPI
  module Models
    module Sandbox
      type job_create_params =
        { type: FinchAPI::Models::Sandbox::JobCreateParams::type_ }
        & FinchAPI::Internal::Type::request_parameters

      class JobCreateParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor type: FinchAPI::Models::Sandbox::JobCreateParams::type_

        def initialize: (
          type: FinchAPI::Models::Sandbox::JobCreateParams::type_,
          ?request_options: FinchAPI::request_opts
        ) -> void

        type type_ = :data_sync_all

        module Type
          extend FinchAPI::Internal::Type::Enum

          DATA_SYNC_ALL: :data_sync_all

          def self?.values: -> ::Array[FinchAPI::Models::Sandbox::JobCreateParams::type_]
        end
      end
    end
  end
end
