module FinchAPI
  module Models
    module Sandbox
      type payment_create_params =
        {
          end_date: String,
          pay_statements: ::Array[FinchAPI::HRIS::PayStatement],
          start_date: String
        }
        & FinchAPI::Internal::Type::request_parameters

      class PaymentCreateParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_reader end_date: String?

        def end_date=: (String) -> String

        attr_reader pay_statements: ::Array[FinchAPI::HRIS::PayStatement]?

        def pay_statements=: (
          ::Array[FinchAPI::HRIS::PayStatement]
        ) -> ::Array[FinchAPI::HRIS::PayStatement]

        attr_reader start_date: String?

        def start_date=: (String) -> String

        def initialize: (
          ?end_date: String,
          ?pay_statements: ::Array[FinchAPI::HRIS::PayStatement],
          ?start_date: String,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          end_date: String,
          pay_statements: ::Array[FinchAPI::HRIS::PayStatement],
          start_date: String,
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
