module FinchAPI
  module Models
    module HRIS
      type benefit_features_and_operations =
        {
          supported_features: FinchAPI::HRIS::SupportedBenefit,
          supported_operations: FinchAPI::HRIS::SupportPerBenefitType
        }

      class BenefitFeaturesAndOperations < FinchAPI::Internal::Type::BaseModel
        attr_reader supported_features: FinchAPI::HRIS::SupportedBenefit?

        def supported_features=: (
          FinchAPI::HRIS::SupportedBenefit
        ) -> FinchAPI::HRIS::SupportedBenefit

        attr_reader supported_operations: FinchAPI::HRIS::SupportPerBenefitType?

        def supported_operations=: (
          FinchAPI::HRIS::SupportPerBenefitType
        ) -> FinchAPI::HRIS::SupportPerBenefitType

        def initialize: (
          ?supported_features: FinchAPI::HRIS::SupportedBenefit,
          ?supported_operations: FinchAPI::HRIS::SupportPerBenefitType
        ) -> void

        def to_hash: -> {
          supported_features: FinchAPI::HRIS::SupportedBenefit,
          supported_operations: FinchAPI::HRIS::SupportPerBenefitType
        }
      end
    end
  end
end
