module FinchAPI
  module Models
    module HRIS
      type benefit_contribution =
        { amount: Integer?, type: FinchAPI::HRIS::BenefitContribution::type_? }

      class BenefitContribution < FinchAPI::Internal::Type::BaseModel
        attr_accessor amount: Integer?

        attr_accessor type: FinchAPI::HRIS::BenefitContribution::type_?

        def initialize: (
          ?amount: Integer?,
          ?type: FinchAPI::HRIS::BenefitContribution::type_?
        ) -> void

        type type_ = :fixed | :percent

        module Type
          extend FinchAPI::Internal::Type::Enum

          FIXED: :fixed
          PERCENT: :percent

          def self?.values: -> ::Array[FinchAPI::HRIS::BenefitContribution::type_]
        end
      end
    end
  end
end
