module FinchAPI
  module Models
    module HRIS
      type benefit_retrieve_params =
        {  } & FinchAPI::Internal::Type::request_parameters

      class BenefitRetrieveParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        def initialize: (?request_options: FinchAPI::request_opts) -> void
      end
    end
  end
end
