module FinchAPI
  module Models
    module HRIS
      type benefit_contribution =
        {
          amount: Integer?,
          type: FinchAPI::Models::HRIS::BenefitContribution::type_?
        }

      class BenefitContribution < FinchAPI::Internal::Type::BaseModel
        attr_accessor amount: Integer?

        attr_accessor type: FinchAPI::Models::HRIS::BenefitContribution::type_?

        def initialize: (
          ?amount: Integer?,
          ?type: FinchAPI::Models::HRIS::BenefitContribution::type_?
        ) -> void

        def to_hash: -> FinchAPI::Models::HRIS::benefit_contribution

        type type_ = :fixed | :percent

        module Type
          extend FinchAPI::Internal::Type::Enum

          FIXED: :fixed
          PERCENT: :percent

          def self?.values: -> ::Array[FinchAPI::Models::HRIS::BenefitContribution::type_]
        end
      end
    end
  end
end
