module FinchAPI
  module Models
    module HRIS
      type benefit_update_params =
        { benefit_id: String, entity_ids: ::Array[String], description: String }
        & FinchAPI::Internal::Type::request_parameters

      class BenefitUpdateParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor benefit_id: String

        attr_reader entity_ids: ::Array[String]?

        def entity_ids=: (::Array[String]) -> ::Array[String]

        attr_reader description: String?

        def description=: (String) -> String

        def initialize: (
          benefit_id: String,
          ?entity_ids: ::Array[String],
          ?description: String,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          benefit_id: String,
          entity_ids: ::Array[String],
          description: String,
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
