module FinchAPI
  module Models
    module HRIS
      type benefit_frequency = :one_time | :every_paycheck | :monthly

      module BenefitFrequency
        extend FinchAPI::Internal::Type::Enum

        ONE_TIME: :one_time
        EVERY_PAYCHECK: :every_paycheck
        MONTHLY: :monthly

        def self?.values: -> ::Array[FinchAPI::Models::HRIS::benefit_frequency]
      end
    end
  end
end
