module FinchAPI
  module Models
    module HRIS
      type benefits_support =
        {
          commuter: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          custom_post_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          custom_pre_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          fsa_dependent_care: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          fsa_medical: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          hsa_post: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          hsa_pre: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          :s125_dental => FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          :s125_medical => FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          :s125_vision => FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          simple: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          simple_ira: FinchAPI::HRIS::BenefitFeaturesAndOperations?
        }

      class BenefitsSupport < FinchAPI::Internal::Type::BaseModel
        attr_accessor commuter: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor custom_post_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor custom_pre_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor fsa_dependent_care: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor fsa_medical: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor hsa_post: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor hsa_pre: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor s125_dental: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor s125_medical: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor s125_vision: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor simple: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        attr_accessor simple_ira: FinchAPI::HRIS::BenefitFeaturesAndOperations?

        def initialize: (
          ?commuter: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?custom_post_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?custom_pre_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?fsa_dependent_care: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?fsa_medical: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?hsa_post: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?hsa_pre: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?s125_dental: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?s125_medical: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?s125_vision: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?simple: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          ?simple_ira: FinchAPI::HRIS::BenefitFeaturesAndOperations?
        ) -> void

        def to_hash: -> {
          commuter: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          custom_post_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          custom_pre_tax: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          fsa_dependent_care: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          fsa_medical: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          hsa_post: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          hsa_pre: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          :s125_dental => FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          :s125_medical => FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          :s125_vision => FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          simple: FinchAPI::HRIS::BenefitFeaturesAndOperations?,
          simple_ira: FinchAPI::HRIS::BenefitFeaturesAndOperations?
        }
      end
    end
  end
end
