module FinchAPI
  module Models
    module HRIS
      type company_benefit =
        {
          benefit_id: String,
          description: String?,
          frequency: FinchAPI::Models::HRIS::benefit_frequency?,
          type: FinchAPI::Models::HRIS::benefit_type?
        }

      class CompanyBenefit < FinchAPI::BaseModel
        attr_accessor benefit_id: String

        attr_accessor description: String?

        attr_accessor frequency: FinchAPI::Models::HRIS::benefit_frequency?

        attr_accessor type: FinchAPI::Models::HRIS::benefit_type?

        def initialize: (
          benefit_id: String,
          description: String?,
          frequency: FinchAPI::Models::HRIS::benefit_frequency?,
          type: FinchAPI::Models::HRIS::benefit_type?
        ) -> void

        def to_hash: -> FinchAPI::Models::HRIS::company_benefit
      end
    end
  end
end
