module FinchAPI
  module Models
    module HRIS
      type create_company_benefits_response = { benefit_id: String }

      class CreateCompanyBenefitsResponse < FinchAPI::Internal::Type::BaseModel
        attr_accessor benefit_id: String

        def initialize: (benefit_id: String) -> void

        def to_hash: -> FinchAPI::Models::HRIS::create_company_benefits_response
      end
    end
  end
end
