module FinchAPI
  module Models
    module HRIS
      type directory_list_individuals_params =
        { limit: Integer, offset: Integer }
        & FinchAPI::Internal::Type::request_parameters

      class DirectoryListIndividualsParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        def initialize: (
          ?limit: Integer,
          ?offset: Integer,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          limit: Integer,
          offset: Integer,
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
