module FinchAPI
  module Models
    module HRIS
      type directory_list_params =
        { entity_ids: ::Array[String], limit: Integer, offset: Integer }
        & FinchAPI::Internal::Type::request_parameters

      class DirectoryListParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_reader entity_ids: ::Array[String]?

        def entity_ids=: (::Array[String]) -> ::Array[String]

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        def initialize: (
          ?entity_ids: ::Array[String],
          ?limit: Integer,
          ?offset: Integer,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          entity_ids: ::Array[String],
          limit: Integer,
          offset: Integer,
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
