module FinchAPI
  module Models
    module HRIS
      type document_list_response =
        {
          documents: ::Array[FinchAPI::HRIS::DocumentResponse],
          paging: FinchAPI::Paging
        }

      class DocumentListResponse < FinchAPI::Internal::Type::BaseModel
        attr_accessor documents: ::Array[FinchAPI::HRIS::DocumentResponse]

        attr_accessor paging: FinchAPI::Paging

        def initialize: (
          documents: ::Array[FinchAPI::HRIS::DocumentResponse],
          paging: FinchAPI::Paging
        ) -> void
      end
    end
  end
end
