module FinchAPI
  module Models
    module HRIS
      type document_retreive_response =
        FinchAPI::Models::HRIS::W42020 | FinchAPI::Models::HRIS::W42005

      module DocumentRetreiveResponse
        extend FinchAPI::Internal::Type::Union

        def self?.variants: -> [FinchAPI::Models::HRIS::W42020, FinchAPI::Models::HRIS::W42005]
      end
    end
  end
end
