module FinchAPI
  module Models
    module HRIS
      type document_retreive_params =
        { entity_ids: ::Array[String] }
        & FinchAPI::Internal::Type::request_parameters

      class DocumentRetreiveParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor entity_ids: ::Array[String]

        def initialize: (
          entity_ids: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          entity_ids: ::Array[String],
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
