module FinchAPI
  module Models
    module HRIS
      type employment_data_response =
        {
          body: FinchAPI::Models::HRIS::employment_data,
          code: Integer,
          individual_id: String
        }

      class EmploymentDataResponse < FinchAPI::Internal::Type::BaseModel
        attr_accessor body: FinchAPI::Models::HRIS::employment_data

        attr_accessor code: Integer

        attr_accessor individual_id: String

        def initialize: (
          body: FinchAPI::Models::HRIS::employment_data,
          code: Integer,
          individual_id: String
        ) -> void

        def to_hash: -> FinchAPI::Models::HRIS::employment_data_response
      end
    end
  end
end
