module FinchAPI
  module Models
    module HRIS
      type employment_retrieve_many_params =
        {
          requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request]
        }
        & FinchAPI::Internal::Type::request_parameters

      class EmploymentRetrieveManyParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request]

        def initialize: (
          requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request],
          ?request_options: FinchAPI::request_opts
        ) -> void

        type request = { individual_id: String }

        class Request < FinchAPI::Internal::Type::BaseModel
          attr_accessor individual_id: String

          def initialize: (individual_id: String) -> void
        end
      end
    end
  end
end
