module FinchAPI
  module Models
    module HRIS
      type employment_retrieve_many_params =
        {
          entity_ids: ::Array[String],
          requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request]
        }
        & FinchAPI::Internal::Type::request_parameters

      class EmploymentRetrieveManyParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor entity_ids: ::Array[String]

        attr_accessor requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request]

        def initialize: (
          entity_ids: ::Array[String],
          requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request],
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          entity_ids: ::Array[String],
          requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request],
          request_options: FinchAPI::RequestOptions
        }

        type request = { individual_id: String }

        class Request < FinchAPI::Internal::Type::BaseModel
          attr_accessor individual_id: String

          def initialize: (individual_id: String) -> void

          def to_hash: -> { individual_id: String }
        end
      end
    end
  end
end
