module FinchAPI
  module Models
    module HRIS
      type individual_retrieve_many_params =
        {
          requests: ::Array[FinchAPI::HRIS::IndividualRetrieveManyParams::Request],
          entity_ids: ::Array[String],
          options: FinchAPI::HRIS::IndividualRetrieveManyParams::Options?
        }
        & FinchAPI::Internal::Type::request_parameters

      class IndividualRetrieveManyParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor requests: ::Array[FinchAPI::HRIS::IndividualRetrieveManyParams::Request]

        attr_reader entity_ids: ::Array[String]?

        def entity_ids=: (::Array[String]) -> ::Array[String]

        attr_accessor options: FinchAPI::HRIS::IndividualRetrieveManyParams::Options?

        def initialize: (
          requests: ::Array[FinchAPI::HRIS::IndividualRetrieveManyParams::Request],
          ?entity_ids: ::Array[String],
          ?options: FinchAPI::HRIS::IndividualRetrieveManyParams::Options?,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          requests: ::Array[FinchAPI::HRIS::IndividualRetrieveManyParams::Request],
          entity_ids: ::Array[String],
          options: FinchAPI::HRIS::IndividualRetrieveManyParams::Options?,
          request_options: FinchAPI::RequestOptions
        }

        type request = { individual_id: String }

        class Request < FinchAPI::Internal::Type::BaseModel
          attr_accessor individual_id: String

          def initialize: (individual_id: String) -> void

          def to_hash: -> { individual_id: String }
        end

        type options = { include: ::Array[String] }

        class Options < FinchAPI::Internal::Type::BaseModel
          attr_reader include: ::Array[String]?

          def include=: (::Array[String]) -> ::Array[String]

          def initialize: (?include: ::Array[String]) -> void

          def to_hash: -> { include: ::Array[String] }
        end
      end
    end
  end
end
