module FinchAPI
  module Models
    module HRIS
      type individual_response =
        {
          body: FinchAPI::Models::HRIS::individual,
          code: Integer,
          individual_id: String
        }

      class IndividualResponse < FinchAPI::Internal::Type::BaseModel
        attr_accessor body: FinchAPI::Models::HRIS::individual

        attr_accessor code: Integer

        attr_accessor individual_id: String

        def initialize: (
          body: FinchAPI::Models::HRIS::individual,
          code: Integer,
          individual_id: String
        ) -> void
      end
    end
  end
end
