module FinchAPI
  module Models
    module HRIS
      type pay_statement =
        {
          earnings: ::Array[FinchAPI::HRIS::PayStatement::Earning?]?,
          employee_deductions: ::Array[FinchAPI::HRIS::PayStatement::EmployeeDeduction?]?,
          employer_contributions: ::Array[FinchAPI::HRIS::PayStatement::EmployerContribution?]?,
          gross_pay: FinchAPI::Money?,
          individual_id: String,
          net_pay: FinchAPI::Money?,
          payment_method: FinchAPI::HRIS::PayStatement::payment_method?,
          taxes: ::Array[FinchAPI::HRIS::PayStatement::Tax?]?,
          total_hours: Float?,
          type: FinchAPI::HRIS::PayStatement::type_?
        }

      class PayStatement < FinchAPI::Internal::Type::BaseModel
        attr_accessor earnings: ::Array[FinchAPI::HRIS::PayStatement::Earning?]?

        attr_accessor employee_deductions: ::Array[FinchAPI::HRIS::PayStatement::EmployeeDeduction?]?

        attr_accessor employer_contributions: ::Array[FinchAPI::HRIS::PayStatement::EmployerContribution?]?

        attr_accessor gross_pay: FinchAPI::Money?

        attr_reader individual_id: String?

        def individual_id=: (String) -> String

        attr_accessor net_pay: FinchAPI::Money?

        attr_accessor payment_method: FinchAPI::HRIS::PayStatement::payment_method?

        attr_accessor taxes: ::Array[FinchAPI::HRIS::PayStatement::Tax?]?

        attr_accessor total_hours: Float?

        attr_accessor type: FinchAPI::HRIS::PayStatement::type_?

        def initialize: (
          ?earnings: ::Array[FinchAPI::HRIS::PayStatement::Earning?]?,
          ?employee_deductions: ::Array[FinchAPI::HRIS::PayStatement::EmployeeDeduction?]?,
          ?employer_contributions: ::Array[FinchAPI::HRIS::PayStatement::EmployerContribution?]?,
          ?gross_pay: FinchAPI::Money?,
          ?individual_id: String,
          ?net_pay: FinchAPI::Money?,
          ?payment_method: FinchAPI::HRIS::PayStatement::payment_method?,
          ?taxes: ::Array[FinchAPI::HRIS::PayStatement::Tax?]?,
          ?total_hours: Float?,
          ?type: FinchAPI::HRIS::PayStatement::type_?
        ) -> void

        type earning =
          {
            amount: Integer?,
            attributes: FinchAPI::HRIS::PayStatement::Earning::Attributes?,
            currency: String?,
            hours: Float?,
            name: String?,
            type: FinchAPI::HRIS::PayStatement::Earning::type_?
          }

        class Earning < FinchAPI::Internal::Type::BaseModel
          attr_accessor amount: Integer?

          attr_accessor attributes: FinchAPI::HRIS::PayStatement::Earning::Attributes?

          attr_accessor currency: String?

          attr_accessor hours: Float?

          attr_accessor name: String?

          attr_accessor type: FinchAPI::HRIS::PayStatement::Earning::type_?

          def initialize: (
            ?amount: Integer?,
            ?attributes: FinchAPI::HRIS::PayStatement::Earning::Attributes?,
            ?currency: String?,
            ?hours: Float?,
            ?name: String?,
            ?type: FinchAPI::HRIS::PayStatement::Earning::type_?
          ) -> void

          type attributes =
            {
              metadata: FinchAPI::HRIS::PayStatement::Earning::Attributes::Metadata
            }

          class Attributes < FinchAPI::Internal::Type::BaseModel
            attr_reader metadata: FinchAPI::HRIS::PayStatement::Earning::Attributes::Metadata?

            def metadata=: (
              FinchAPI::HRIS::PayStatement::Earning::Attributes::Metadata
            ) -> FinchAPI::HRIS::PayStatement::Earning::Attributes::Metadata

            def initialize: (
              ?metadata: FinchAPI::HRIS::PayStatement::Earning::Attributes::Metadata
            ) -> void

            type metadata = { metadata: ::Hash[Symbol, top?] }

            class Metadata < FinchAPI::Internal::Type::BaseModel
              attr_reader metadata: ::Hash[Symbol, top?]?

              def metadata=: (::Hash[Symbol, top?]) -> ::Hash[Symbol, top?]

              def initialize: (?metadata: ::Hash[Symbol, top?]) -> void
            end
          end

          type type_ =
            :salary
            | :wage
            | :reimbursement
            | :overtime
            | :severance
            | :double_overtime
            | :pto
            | :sick
            | :bonus
            | :commission
            | :tips
            | :"1099"
            | :other

          module Type
            extend FinchAPI::Internal::Type::Enum

            SALARY: :salary
            WAGE: :wage
            REIMBURSEMENT: :reimbursement
            OVERTIME: :overtime
            SEVERANCE: :severance
            DOUBLE_OVERTIME: :double_overtime
            PTO: :pto
            SICK: :sick
            BONUS: :bonus
            COMMISSION: :commission
            TIPS: :tips
            TYPE_1099: :"1099"
            OTHER: :other

            def self?.values: -> ::Array[FinchAPI::HRIS::PayStatement::Earning::type_]
          end
        end

        type employee_deduction =
          {
            amount: Integer?,
            attributes: FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes?,
            currency: String?,
            name: String?,
            pre_tax: bool?,
            type: FinchAPI::Models::HRIS::benefit_type?
          }

        class EmployeeDeduction < FinchAPI::Internal::Type::BaseModel
          attr_accessor amount: Integer?

          attr_accessor attributes: FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes?

          attr_accessor currency: String?

          attr_accessor name: String?

          attr_accessor pre_tax: bool?

          attr_accessor type: FinchAPI::Models::HRIS::benefit_type?

          def initialize: (
            ?amount: Integer?,
            ?attributes: FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes?,
            ?currency: String?,
            ?name: String?,
            ?pre_tax: bool?,
            ?type: FinchAPI::Models::HRIS::benefit_type?
          ) -> void

          type attributes =
            {
              metadata: FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes::Metadata
            }

          class Attributes < FinchAPI::Internal::Type::BaseModel
            attr_reader metadata: FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes::Metadata?

            def metadata=: (
              FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes::Metadata
            ) -> FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes::Metadata

            def initialize: (
              ?metadata: FinchAPI::HRIS::PayStatement::EmployeeDeduction::Attributes::Metadata
            ) -> void

            type metadata = { metadata: ::Hash[Symbol, top?] }

            class Metadata < FinchAPI::Internal::Type::BaseModel
              attr_reader metadata: ::Hash[Symbol, top?]?

              def metadata=: (::Hash[Symbol, top?]) -> ::Hash[Symbol, top?]

              def initialize: (?metadata: ::Hash[Symbol, top?]) -> void
            end
          end
        end

        type employer_contribution =
          {
            amount: Integer?,
            attributes: FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes?,
            currency: String?,
            name: String?,
            type: FinchAPI::Models::HRIS::benefit_type?
          }

        class EmployerContribution < FinchAPI::Internal::Type::BaseModel
          attr_accessor amount: Integer?

          attr_accessor attributes: FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes?

          attr_accessor currency: String?

          attr_accessor name: String?

          attr_accessor type: FinchAPI::Models::HRIS::benefit_type?

          def initialize: (
            ?amount: Integer?,
            ?attributes: FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes?,
            ?currency: String?,
            ?name: String?,
            ?type: FinchAPI::Models::HRIS::benefit_type?
          ) -> void

          type attributes =
            {
              metadata: FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes::Metadata
            }

          class Attributes < FinchAPI::Internal::Type::BaseModel
            attr_reader metadata: FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes::Metadata?

            def metadata=: (
              FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes::Metadata
            ) -> FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes::Metadata

            def initialize: (
              ?metadata: FinchAPI::HRIS::PayStatement::EmployerContribution::Attributes::Metadata
            ) -> void

            type metadata = { metadata: ::Hash[Symbol, top?] }

            class Metadata < FinchAPI::Internal::Type::BaseModel
              attr_reader metadata: ::Hash[Symbol, top?]?

              def metadata=: (::Hash[Symbol, top?]) -> ::Hash[Symbol, top?]

              def initialize: (?metadata: ::Hash[Symbol, top?]) -> void
            end
          end
        end

        type payment_method = :check | :direct_deposit | :other

        module PaymentMethod
          extend FinchAPI::Internal::Type::Enum

          CHECK: :check
          DIRECT_DEPOSIT: :direct_deposit
          OTHER: :other

          def self?.values: -> ::Array[FinchAPI::HRIS::PayStatement::payment_method]
        end

        type tax =
          {
            amount: Integer?,
            attributes: FinchAPI::HRIS::PayStatement::Tax::Attributes?,
            currency: String?,
            employer: bool?,
            name: String?,
            type: FinchAPI::HRIS::PayStatement::Tax::type_?
          }

        class Tax < FinchAPI::Internal::Type::BaseModel
          attr_accessor amount: Integer?

          attr_accessor attributes: FinchAPI::HRIS::PayStatement::Tax::Attributes?

          attr_accessor currency: String?

          attr_accessor employer: bool?

          attr_accessor name: String?

          attr_accessor type: FinchAPI::HRIS::PayStatement::Tax::type_?

          def initialize: (
            ?amount: Integer?,
            ?attributes: FinchAPI::HRIS::PayStatement::Tax::Attributes?,
            ?currency: String?,
            ?employer: bool?,
            ?name: String?,
            ?type: FinchAPI::HRIS::PayStatement::Tax::type_?
          ) -> void

          type attributes =
            {
              metadata: FinchAPI::HRIS::PayStatement::Tax::Attributes::Metadata
            }

          class Attributes < FinchAPI::Internal::Type::BaseModel
            attr_reader metadata: FinchAPI::HRIS::PayStatement::Tax::Attributes::Metadata?

            def metadata=: (
              FinchAPI::HRIS::PayStatement::Tax::Attributes::Metadata
            ) -> FinchAPI::HRIS::PayStatement::Tax::Attributes::Metadata

            def initialize: (
              ?metadata: FinchAPI::HRIS::PayStatement::Tax::Attributes::Metadata
            ) -> void

            type metadata = { metadata: ::Hash[Symbol, top?] }

            class Metadata < FinchAPI::Internal::Type::BaseModel
              attr_reader metadata: ::Hash[Symbol, top?]?

              def metadata=: (::Hash[Symbol, top?]) -> ::Hash[Symbol, top?]

              def initialize: (?metadata: ::Hash[Symbol, top?]) -> void
            end
          end

          type type_ = :state | :federal | :local | :fica

          module Type
            extend FinchAPI::Internal::Type::Enum

            STATE: :state
            FEDERAL: :federal
            LOCAL: :local
            FICA: :fica

            def self?.values: -> ::Array[FinchAPI::HRIS::PayStatement::Tax::type_]
          end
        end

        type type_ = :regular_payroll | :off_cycle_payroll | :one_time_payment

        module Type
          extend FinchAPI::Internal::Type::Enum

          REGULAR_PAYROLL: :regular_payroll
          OFF_CYCLE_PAYROLL: :off_cycle_payroll
          ONE_TIME_PAYMENT: :one_time_payment

          def self?.values: -> ::Array[FinchAPI::HRIS::PayStatement::type_]
        end
      end
    end
  end
end
