module FinchAPI
  module Models
    module HRIS
      type pay_statement_response =
        {
          body: FinchAPI::HRIS::PayStatementResponseBody,
          code: Integer,
          payment_id: String
        }

      class PayStatementResponse < FinchAPI::Internal::Type::BaseModel
        attr_accessor body: FinchAPI::HRIS::PayStatementResponseBody

        attr_accessor code: Integer

        attr_accessor payment_id: String

        def initialize: (
          body: FinchAPI::HRIS::PayStatementResponseBody,
          code: Integer,
          payment_id: String
        ) -> void
      end
    end
  end
end
