module FinchAPI
  module Models
    module HRIS
      type pay_statement_response_body =
        {
          paging: FinchAPI::Paging,
          pay_statements: ::Array[FinchAPI::HRIS::PayStatement]
        }

      class PayStatementResponseBody < FinchAPI::Internal::Type::BaseModel
        attr_reader paging: FinchAPI::Paging?

        def paging=: (FinchAPI::Paging) -> FinchAPI::Paging

        attr_reader pay_statements: ::Array[FinchAPI::HRIS::PayStatement]?

        def pay_statements=: (
          ::Array[FinchAPI::HRIS::PayStatement]
        ) -> ::Array[FinchAPI::HRIS::PayStatement]

        def initialize: (
          ?paging: FinchAPI::Paging,
          ?pay_statements: ::Array[FinchAPI::HRIS::PayStatement]
        ) -> void

        def to_hash: -> {
          paging: FinchAPI::Paging,
          pay_statements: ::Array[FinchAPI::HRIS::PayStatement]
        }
      end
    end
  end
end
