module FinchAPI
  module Models
    module HRIS
      type payment_list_params =
        { end_date: Date, entity_ids: ::Array[String], start_date: Date }
        & FinchAPI::Internal::Type::request_parameters

      class PaymentListParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor end_date: Date

        attr_accessor entity_ids: ::Array[String]

        attr_accessor start_date: Date

        def initialize: (
          end_date: Date,
          entity_ids: ::Array[String],
          start_date: Date,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          end_date: Date,
          entity_ids: ::Array[String],
          start_date: Date,
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
