module FinchAPI
  module Models
    module HRIS
      type supported_benefit =
        {
          annual_maximum: bool?,
          company_contribution: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::company_contribution?]?,
          description: String?,
          employee_deduction: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::employee_deduction?]?,
          frequencies: ::Array[FinchAPI::Models::HRIS::benefit_frequency?],
          catch_up: bool?,
          hsa_contribution_limit: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::hsa_contribution_limit?]?
        }

      class SupportedBenefit < FinchAPI::Internal::Type::BaseModel
        attr_accessor annual_maximum: bool?

        attr_accessor company_contribution: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::company_contribution?]?

        attr_accessor description: String?

        attr_accessor employee_deduction: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::employee_deduction?]?

        attr_accessor frequencies: ::Array[FinchAPI::Models::HRIS::benefit_frequency?]

        attr_accessor catch_up: bool?

        attr_accessor hsa_contribution_limit: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::hsa_contribution_limit?]?

        def initialize: (
          annual_maximum: bool?,
          company_contribution: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::company_contribution?]?,
          description: String?,
          employee_deduction: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::employee_deduction?]?,
          frequencies: ::Array[FinchAPI::Models::HRIS::benefit_frequency?],
          ?catch_up: bool?,
          ?hsa_contribution_limit: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::hsa_contribution_limit?]?
        ) -> void

        def to_hash: -> {
          annual_maximum: bool?,
          company_contribution: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::company_contribution?]?,
          description: String?,
          employee_deduction: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::employee_deduction?]?,
          frequencies: ::Array[FinchAPI::Models::HRIS::benefit_frequency?],
          catch_up: bool?,
          hsa_contribution_limit: ::Array[FinchAPI::Models::HRIS::SupportedBenefit::hsa_contribution_limit?]?
        }

        type company_contribution = :fixed | :percent | :tiered

        module CompanyContribution
          extend FinchAPI::Internal::Type::Enum

          FIXED: :fixed
          PERCENT: :percent
          TIERED: :tiered

          def self?.values: -> ::Array[FinchAPI::Models::HRIS::SupportedBenefit::company_contribution]
        end

        type employee_deduction = :fixed | :percent

        module EmployeeDeduction
          extend FinchAPI::Internal::Type::Enum

          FIXED: :fixed
          PERCENT: :percent

          def self?.values: -> ::Array[FinchAPI::Models::HRIS::SupportedBenefit::employee_deduction]
        end

        type hsa_contribution_limit = :family | :individual

        module HsaContributionLimit
          extend FinchAPI::Internal::Type::Enum

          FAMILY: :family
          INDIVIDUAL: :individual

          def self?.values: -> ::Array[FinchAPI::Models::HRIS::SupportedBenefit::hsa_contribution_limit]
        end
      end
    end
  end
end
