module FinchAPI
  module Models
    module HRIS
      type support_per_benefit_type =
        {
          company_benefits: FinchAPI::OperationSupportMatrix,
          individual_benefits: FinchAPI::OperationSupportMatrix
        }

      class SupportPerBenefitType < FinchAPI::Internal::Type::BaseModel
        attr_reader company_benefits: FinchAPI::OperationSupportMatrix?

        def company_benefits=: (
          FinchAPI::OperationSupportMatrix
        ) -> FinchAPI::OperationSupportMatrix

        attr_reader individual_benefits: FinchAPI::OperationSupportMatrix?

        def individual_benefits=: (
          FinchAPI::OperationSupportMatrix
        ) -> FinchAPI::OperationSupportMatrix

        def initialize: (
          ?company_benefits: FinchAPI::OperationSupportMatrix,
          ?individual_benefits: FinchAPI::OperationSupportMatrix
        ) -> void
      end
    end
  end
end
