module FinchAPI
  module Models
    type access_token_create_params =
      {
        code: String,
        client_id: String,
        client_secret: String,
        redirect_uri: String
      }
      & FinchAPI::request_parameters

    class AccessTokenCreateParams < FinchAPI::BaseModel
      extend FinchAPI::RequestParameters::Converter
      include FinchAPI::RequestParameters

      attr_accessor code: String

      attr_reader client_id: String?

      def client_id=: (String) -> String

      attr_reader client_secret: String?

      def client_secret=: (String) -> String

      attr_reader redirect_uri: String?

      def redirect_uri=: (String) -> String

      def initialize:
        (
          code: String,
          ?client_id: String,
          ?client_secret: String,
          ?redirect_uri: String,
          ?request_options: FinchAPI::request_opts
        ) -> void
        | (
          ?FinchAPI::Models::access_token_create_params
          | FinchAPI::BaseModel data
        ) -> void

      def to_hash: -> FinchAPI::Models::access_token_create_params
    end
  end
end
