module FinchAPI
  module Models
    type base_webhook_event =
      { account_id: String, company_id: String, connection_id: String }

    class BaseWebhookEvent < FinchAPI::BaseModel
      attr_accessor account_id: String

      attr_accessor company_id: String

      attr_reader connection_id: String?

      def connection_id=: (String) -> String

      def initialize:
        (account_id: String, company_id: String, ?connection_id: String) -> void
        | (
          ?FinchAPI::Models::base_webhook_event | FinchAPI::BaseModel data
        ) -> void

      def to_hash: -> FinchAPI::Models::base_webhook_event
    end
  end
end
