module FinchAPI
  module Models
    type connection_status_type =
      :pending
      | :processing
      | :connected
      | :error_no_account_setup
      | :error_permissions
      | :reauth

    module ConnectionStatusType
      extend FinchAPI::Enum

      PENDING: :pending
      PROCESSING: :processing
      CONNECTED: :connected
      ERROR_NO_ACCOUNT_SETUP: :error_no_account_setup
      ERROR_PERMISSIONS: :error_permissions
      REAUTH: :reauth

      def self?.values: -> ::Array[FinchAPI::Models::connection_status_type]
    end
  end
end
