module FinchAPI
  module Models
    type paging = { count: Integer, offset: Integer }

    class Paging < FinchAPI::BaseModel
      attr_reader count: Integer?

      def count=: (Integer) -> Integer

      attr_reader offset: Integer?

      def offset=: (Integer) -> Integer

      def initialize:
        (count: Integer, offset: Integer) -> void
        | (?FinchAPI::Models::paging | FinchAPI::BaseModel data) -> void

      def to_hash: -> FinchAPI::Models::paging
    end
  end
end
