module FinchAPI
  module Models
    type webhook_event =
      FinchAPI::Models::AccountUpdateEvent
      | FinchAPI::Models::CompanyEvent
      | FinchAPI::Models::JobCompletionEvent
      | FinchAPI::Models::DirectoryEvent
      | FinchAPI::Models::EmploymentEvent
      | FinchAPI::Models::IndividualEvent
      | FinchAPI::Models::PaymentEvent
      | FinchAPI::Models::PayStatementEvent

    module WebhookEvent
      extend FinchAPI::Union

      def self.variants: -> [FinchAPI::Models::AccountUpdateEvent, FinchAPI::Models::CompanyEvent, FinchAPI::Models::JobCompletionEvent, FinchAPI::Models::DirectoryEvent, FinchAPI::Models::EmploymentEvent, FinchAPI::Models::IndividualEvent, FinchAPI::Models::PaymentEvent, FinchAPI::Models::PayStatementEvent]
    end
  end
end
