module FinchAPI
  module Models
    type webhook_event =
      FinchAPI::Models::AccountUpdateEvent
      | FinchAPI::Models::JobCompletionEvent
      | FinchAPI::Models::CompanyEvent
      | FinchAPI::Models::DirectoryEvent
      | FinchAPI::Models::EmploymentEvent
      | FinchAPI::Models::IndividualEvent
      | FinchAPI::Models::PaymentEvent
      | FinchAPI::Models::PayStatementEvent

    class WebhookEvent < FinchAPI::Union
      private def self.variants: -> [[nil, FinchAPI::Models::AccountUpdateEvent], [nil, FinchAPI::Models::JobCompletionEvent], [nil, FinchAPI::Models::CompanyEvent], [nil, FinchAPI::Models::DirectoryEvent], [nil, FinchAPI::Models::EmploymentEvent], [nil, FinchAPI::Models::IndividualEvent], [nil, FinchAPI::Models::PaymentEvent], [nil, FinchAPI::Models::PayStatementEvent]]
    end
  end
end
