module FinchAPI
  class Page[Elem]
    include FinchAPI::BasePage[Elem]

    attr_accessor data: ::Array[Elem]?

    attr_accessor paging: FinchAPI::Models::Paging

    def inspect: -> String
  end
end
