module FinchAPI
  class Unknown = FinchAPI::Type::Unknown

  class BooleanModel = FinchAPI::Type::BooleanModel

  module Enum = FinchAPI::Type::Enum

  module Union = FinchAPI::Type::Union

  class ArrayOf = FinchAPI::Type::ArrayOf

  class HashOf = FinchAPI::Type::HashOf

  class BaseModel = FinchAPI::Type::BaseModel

  type request_parameters = FinchAPI::Type::request_parameters

  module RequestParameters = FinchAPI::Type::RequestParameters

  module Type
  end
end
