module FinchAPI
  module Models
    module HRIS
      class EnrolledIndividualBenefit = Benefits::EnrolledIndividualBenefit

      module Benefits
        type enrolled_individual_benefit = { job_id: String }

        class EnrolledIndividualBenefit < FinchAPI::Internal::Type::BaseModel
          attr_accessor job_id: String

          def initialize: (job_id: String) -> void

          def to_hash: -> FinchAPI::Models::HRIS::Benefits::enrolled_individual_benefit
        end
      end
    end
  end
end
