module FinchAPI
  module Models
    module HRIS
      module Benefits
        type enrolled_individual_benefit_response = { job_id: String }

        class EnrolledIndividualBenefitResponse < FinchAPI::Internal::Type::BaseModel
          attr_accessor job_id: String

          def initialize: (job_id: String) -> void
        end
      end
    end
  end
end
