module FinchAPI
  module Models
    module HRIS
      module Benefits
        type individual_enrolled_ids_response =
          { benefit_id: String, individual_ids: ::Array[String] }

        class IndividualEnrolledIDsResponse < FinchAPI::BaseModel
          attr_accessor benefit_id: String

          attr_accessor individual_ids: ::Array[String]

          def initialize: (
            benefit_id: String,
            individual_ids: ::Array[String]
          ) -> void

          def to_hash: -> FinchAPI::Models::HRIS::Benefits::individual_enrolled_ids_response
        end
      end
    end
  end
end
