module FinchAPI
  module Models
    module HRIS
      module Benefits
        type individual_unenroll_many_response = { job_id: String }

        class IndividualUnenrollManyResponse < FinchAPI::Internal::Type::BaseModel
          attr_accessor job_id: String

          def initialize: (job_id: String) -> void

          def to_hash: -> FinchAPI::Models::HRIS::Benefits::individual_unenroll_many_response
        end
      end
    end
  end
end
