module FinchAPI
  module Resources
    class HRIS
      class Company
        def retrieve:
          (
            ?FinchAPI::Models::HRIS::CompanyRetrieveParams
            | ::Hash[Symbol, top] params
          ) -> FinchAPI::Models::HRIS::HRISCompany
          | (
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::HRIS::HRISCompany

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
