module FinchAPI
  module Resources
    class HRIS
      class Documents
        def list:
          (
            ?FinchAPI::Models::HRIS::DocumentListParams
            | ::Hash[Symbol, top] params
          ) -> FinchAPI::Models::HRIS::DocumentListResponse
          | (
            ?individual_ids: ::Array[String],
            ?limit: Integer,
            ?offset: Integer,
            ?types: ::Array[FinchAPI::Models::HRIS::DocumentListParams::type_],
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::HRIS::DocumentListResponse

        def retreive:
          (
            String document_id,
            ?FinchAPI::Models::HRIS::DocumentRetreiveParams
            | ::Hash[Symbol, top] params
          ) -> FinchAPI::Models::HRIS::document_retreive_response
          | (
            String document_id,
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::HRIS::document_retreive_response

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
