module FinchAPI
  module Models
    module Payroll
      type pay_group_retrieve_response =
        {
          id: String,
          individual_ids: ::Array[String],
          name: String,
          pay_frequencies: ::Array[FinchAPI::Models::Payroll::PayGroupRetrieveResponse::pay_frequency]
        }

      class PayGroupRetrieveResponse < FinchAPI::BaseModel
        attr_accessor id: String

        attr_accessor individual_ids: ::Array[String]

        attr_accessor name: String

        attr_accessor pay_frequencies: ::Array[FinchAPI::Models::Payroll::PayGroupRetrieveResponse::pay_frequency]

        def initialize: (
          id: String,
          individual_ids: ::Array[String],
          name: String,
          pay_frequencies: ::Array[FinchAPI::Models::Payroll::PayGroupRetrieveResponse::pay_frequency]
        ) -> void

        def to_hash: -> FinchAPI::Models::Payroll::pay_group_retrieve_response

        type pay_frequency =
          :annually
          | :semi_annually
          | :quarterly
          | :monthly
          | :semi_monthly
          | :bi_weekly
          | :weekly
          | :daily
          | :other

        module PayFrequency
          extend FinchAPI::Enum

          ANNUALLY: :annually
          SEMI_ANNUALLY: :semi_annually
          QUARTERLY: :quarterly
          MONTHLY: :monthly
          SEMI_MONTHLY: :semi_monthly
          BI_WEEKLY: :bi_weekly
          WEEKLY: :weekly
          DAILY: :daily
          OTHER: :other

          def self?.values: -> ::Array[FinchAPI::Models::Payroll::PayGroupRetrieveResponse::pay_frequency]
        end
      end
    end
  end
end
