module FinchAPI
  module Models
    module Payroll
      type pay_group_list_params =
        {
          entity_ids: ::Array[String],
          individual_id: String,
          pay_frequencies: ::Array[String]
        }
        & FinchAPI::Internal::Type::request_parameters

      class PayGroupListParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor entity_ids: ::Array[String]

        attr_reader individual_id: String?

        def individual_id=: (String) -> String

        attr_reader pay_frequencies: ::Array[String]?

        def pay_frequencies=: (::Array[String]) -> ::Array[String]

        def initialize: (
          entity_ids: ::Array[String],
          ?individual_id: String,
          ?pay_frequencies: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          entity_ids: ::Array[String],
          individual_id: String,
          pay_frequencies: ::Array[String],
          request_options: FinchAPI::RequestOptions
        }
      end
    end
  end
end
