module FinchAPI
  module Models
    module Payroll
      type pay_group_list_params =
        { individual_id: String, pay_frequencies: ::Array[String] }
        & FinchAPI::Internal::Type::request_parameters

      class PayGroupListParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_reader individual_id: String?

        def individual_id=: (String) -> String

        attr_reader pay_frequencies: ::Array[String]?

        def pay_frequencies=: (::Array[String]) -> ::Array[String]

        def initialize: (
          ?individual_id: String,
          ?pay_frequencies: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> void
      end
    end
  end
end
