module FinchAPI
  class IndividualsPage[Elem]
    include FinchAPI::Type::BasePage[Elem]

    attr_accessor individuals: ::Array[Elem]?

    attr_accessor paging: FinchAPI::Models::Paging

    def inspect: -> String
  end
end
