module FinchAPI
  module Models
    module Connect
      type session_new_response = { connect_url: String, session_id: String }

      class SessionNewResponse < FinchAPI::BaseModel
        attr_accessor connect_url: String

        attr_accessor session_id: String

        def initialize:
          (connect_url: String, session_id: String) -> void
          | (
            ?FinchAPI::Models::Connect::session_new_response
            | FinchAPI::BaseModel data
          ) -> void

        def to_hash: -> FinchAPI::Models::Connect::session_new_response
      end
    end
  end
end
