module FinchAPI
  module Models
    module Jobs
      type automated_list_params =
        { limit: Integer, offset: Integer } & FinchAPI::request_parameters

      class AutomatedListParams < FinchAPI::BaseModel
        extend FinchAPI::RequestParameters::Converter
        include FinchAPI::RequestParameters

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader offset: Integer?

        def offset=: (Integer) -> Integer

        def initialize:
          (
            limit: Integer,
            offset: Integer,
            request_options: FinchAPI::request_opts
          ) -> void
          | (
            ?FinchAPI::Models::Jobs::automated_list_params
            | FinchAPI::BaseModel data
          ) -> void

        def to_hash: -> FinchAPI::Models::Jobs::automated_list_params
      end
    end
  end
end
