module FinchAPI
  module Models
    module Jobs
      type automated_retrieve_params = {  } & FinchAPI::request_parameters

      class AutomatedRetrieveParams < FinchAPI::BaseModel
        extend FinchAPI::RequestParameters::Converter
        include FinchAPI::RequestParameters

        def initialize: (?request_options: FinchAPI::request_opts) -> void

        def to_hash: -> FinchAPI::Models::Jobs::automated_retrieve_params
      end
    end
  end
end
