module FinchAPI
  module Models
    module Jobs
      type manual_retrieve_params = {  } & FinchAPI::request_parameters

      class ManualRetrieveParams < FinchAPI::BaseModel
        extend FinchAPI::Type::RequestParameters::Converter
        include FinchAPI::RequestParameters

        def initialize: (?request_options: FinchAPI::request_opts) -> void

        def to_hash: -> FinchAPI::Models::Jobs::manual_retrieve_params
      end
    end
  end
end
