module FinchAPI
  module Models
    module HRIS
      module Benefits
        type unenrolled_individual =
          {
            body: FinchAPI::Models::HRIS::Benefits::UnenrolledIndividual::Body,
            code: Integer,
            individual_id: String
          }

        class UnenrolledIndividual < FinchAPI::BaseModel
          attr_reader body: FinchAPI::Models::HRIS::Benefits::UnenrolledIndividual::Body?

          def body=: (
            FinchAPI::Models::HRIS::Benefits::UnenrolledIndividual::Body
          ) -> FinchAPI::Models::HRIS::Benefits::UnenrolledIndividual::Body

          attr_reader code: Integer?

          def code=: (Integer) -> Integer

          attr_reader individual_id: String?

          def individual_id=: (String) -> String

          def initialize: (
            ?body: FinchAPI::Models::HRIS::Benefits::UnenrolledIndividual::Body,
            ?code: Integer,
            ?individual_id: String
          ) -> void

          def to_hash: -> FinchAPI::Models::HRIS::Benefits::unenrolled_individual

          type body = { finch_code: String?, message: String?, name: String? }

          class Body < FinchAPI::BaseModel
            attr_accessor finch_code: String?

            attr_accessor message: String?

            attr_accessor name: String?

            def initialize: (
              ?finch_code: String?,
              ?message: String?,
              ?name: String?
            ) -> void

            def to_hash: -> FinchAPI::Models::HRIS::Benefits::UnenrolledIndividual::body
          end
        end
      end
    end
  end
end
