module FinchAPI
  module Resources
    class Sandbox
      class Company
        def update: (
          accounts: ::Array[FinchAPI::Sandbox::CompanyUpdateParams::Account]?,
          departments: ::Array[FinchAPI::Sandbox::CompanyUpdateParams::Department?]?,
          ein: String?,
          entity: FinchAPI::Sandbox::CompanyUpdateParams::Entity?,
          legal_name: String?,
          locations: ::Array[FinchAPI::Location?]?,
          primary_email: String?,
          primary_phone_number: String?,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Sandbox::CompanyUpdateResponse

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
