module FinchAPI
  module Resources
    class Sandbox
      class Employment
        def update: (
          String individual_id,
          ?class_code: String?,
          ?custom_fields: ::Array[FinchAPI::Sandbox::EmploymentUpdateParams::CustomField]?,
          ?department: FinchAPI::Sandbox::EmploymentUpdateParams::Department?,
          ?employment: FinchAPI::Sandbox::EmploymentUpdateParams::Employment?,
          ?employment_status: FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment_status?,
          ?end_date: String?,
          ?first_name: String?,
          ?income: FinchAPI::Income?,
          ?income_history: ::Array[FinchAPI::Income?]?,
          ?is_active: bool?,
          ?last_name: String?,
          ?latest_rehire_date: String?,
          ?location: FinchAPI::Location?,
          ?manager: FinchAPI::Sandbox::EmploymentUpdateParams::Manager?,
          ?middle_name: String?,
          ?source_id: String?,
          ?start_date: String?,
          ?title: String?,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Sandbox::EmploymentUpdateResponse

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
