module FinchAPI
  module Resources
    class Sandbox
      class Payment
        def create: (
          ?end_date: String,
          ?pay_statements: ::Array[FinchAPI::Sandbox::PaymentCreateParams::PayStatement],
          ?start_date: String,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Sandbox::PaymentCreateResponse

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
