module FinchAPI
  module Models
    module HRIS
      module Company
        module PayStatementItem
          type rule_update_params =
            { optional_property: top }
            & FinchAPI::Internal::Type::request_parameters

          class RuleUpdateParams < FinchAPI::Internal::Type::BaseModel
            extend FinchAPI::Internal::Type::RequestParameters::Converter
            include FinchAPI::Internal::Type::RequestParameters

            attr_reader optional_property: top?

            def optional_property=: (top) -> top

            def initialize: (
              ?optional_property: top,
              ?request_options: FinchAPI::request_opts
            ) -> void

            def to_hash: -> {
              optional_property: top,
              request_options: FinchAPI::RequestOptions
            }
          end
        end
      end
    end
  end
end
