module FinchAPI
  module Resources
    class AccessTokens
      def create: (
        code: String,
        ?client_id: String,
        ?client_secret: String,
        ?redirect_uri: String,
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::CreateAccessTokenResponse

      def initialize: (client: FinchAPI::Client) -> void
    end
  end
end
