module FinchAPI
  module Resources
    class Account
      def disconnect: (
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::DisconnectResponse

      def disconnect_entity: (
        entity_ids: ::Array[String],
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::DisconnectEntityResponse

      def introspect: (
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::Introspection

      def initialize: (client: FinchAPI::Client) -> void
    end
  end
end
