module FinchAPI
  module Resources
    class RequestForwarding
      def forward: (
        method_: String,
        route: String,
        ?data: String?,
        ?params: ::Hash[Symbol, top?]?,
        ?request_headers: ::Hash[Symbol, top?]?,
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::Models::RequestForwardingForwardResponse

      def initialize: (client: FinchAPI::Client) -> void
    end
  end
end
