module FinchAPI
  module Internal
    module Type
      class Boolean
        extend FinchAPI::Internal::Type::Converter

        def self.===: (top other) -> bool

        def self.==: (top other) -> bool

        def self.coerce: (
          bool | top value,
          state: FinchAPI::Internal::Type::Converter::state
        ) -> (bool | top)

        def self.dump: (bool | top value) -> (bool | top)
      end
    end
  end
end
