module FinchAPI
  module Internal
    module Type
      class Unknown
        extend FinchAPI::Internal::Type::Converter

        def self.===: (top other) -> bool

        def self.==: (top other) -> bool

        def self.coerce: (
          top value,
          state: FinchAPI::Internal::Type::Converter::coerce_state
        ) -> top

        def self.dump: (
          top value,
          state: FinchAPI::Internal::Type::Converter::dump_state
        ) -> top
      end
    end
  end
end
