module FinchAPI
  module Resources
    class Jobs
      class Manual
        def retrieve: (
          String job_id,
          ?entity_id: String,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Jobs::ManualAsyncJob

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
