module FinchAPI
  module Resources
    class Payroll
      class PayGroups
        def retrieve: (
          String pay_group_id,
          ?entity_ids: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Payroll::PayGroupRetrieveResponse

        def list: (
          ?entity_ids: ::Array[String],
          ?individual_id: String,
          ?pay_frequencies: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Internal::SinglePage[FinchAPI::Models::Payroll::PayGroupListResponse]

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
