module FinchAPI
  module Resources
    class HRIS
      class Benefits
        class Individuals
          def enroll_many: (
            String benefit_id,
            ?individuals: ::Array[FinchAPI::Models::HRIS::Benefits::IndividualEnrollManyParams::Individual],
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Internal::SinglePage[FinchAPI::Models::HRIS::Benefits::EnrolledIndividual]

          def enrolled_ids: (
            String benefit_id,
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::HRIS::Benefits::IndividualEnrolledIDsResponse

          def retrieve_many_benefits: (
            String benefit_id,
            ?individual_ids: String,
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Internal::SinglePage[FinchAPI::Models::HRIS::Benefits::IndividualBenefit]

          def unenroll_many: (
            String benefit_id,
            ?individual_ids: ::Array[String],
            ?request_options: FinchAPI::request_opts
          ) -> FinchAPI::Internal::SinglePage[top]

          def initialize: (client: FinchAPI::Client) -> void
        end
      end
    end
  end
end
