module FinchAPI
  module Models
    type access_token_create_params =
      {
        client_id: String,
        client_secret: String,
        code: String,
        redirect_uri: String
      }
      & FinchAPI::Internal::Type::request_parameters

    class AccessTokenCreateParams < FinchAPI::Internal::Type::BaseModel
      extend FinchAPI::Internal::Type::RequestParameters::Converter
      include FinchAPI::Internal::Type::RequestParameters

      attr_accessor client_id: String

      attr_accessor client_secret: String

      attr_accessor code: String

      attr_reader redirect_uri: String?

      def redirect_uri=: (String) -> String

      def initialize: (
        client_id: String,
        client_secret: String,
        code: String,
        ?redirect_uri: String,
        ?request_options: FinchAPI::request_opts
      ) -> void

      def to_hash: -> {
        client_id: String,
        client_secret: String,
        code: String,
        redirect_uri: String,
        request_options: FinchAPI::RequestOptions
      }
    end
  end
end
