module FinchAPI
  module Models
    type account_disconnect_params =
      {  } & FinchAPI::Internal::Type::request_parameters

    class AccountDisconnectParams < FinchAPI::Internal::Type::BaseModel
      extend FinchAPI::Internal::Type::RequestParameters::Converter
      include FinchAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: FinchAPI::request_opts) -> void

      def to_hash: -> FinchAPI::Models::account_disconnect_params
    end
  end
end
