module FinchAPI
  module Models
    type location =
      {
        city: String?,
        country: String?,
        :line1 => String?,
        :line2 => String?,
        postal_code: String?,
        state: String?,
        name: String?,
        source_id: String?
      }

    class Location < FinchAPI::Internal::Type::BaseModel
      attr_accessor city: String?

      attr_accessor country: String?

      attr_accessor line1: String?

      attr_accessor line2: String?

      attr_accessor postal_code: String?

      attr_accessor state: String?

      attr_accessor name: String?

      attr_accessor source_id: String?

      def initialize: (
        city: String?,
        country: String?,
        line1: String?,
        line2: String?,
        postal_code: String?,
        state: String?,
        ?name: String?,
        ?source_id: String?
      ) -> void
    end
  end
end
