module FinchAPI
  module Models
    type money = { amount: Integer?, currency: String }

    class Money < FinchAPI::Internal::Type::BaseModel
      attr_accessor amount: Integer?

      attr_reader currency: String?

      def currency=: (String) -> String

      def initialize: (?amount: Integer?, ?currency: String) -> void

      def to_hash: -> FinchAPI::Models::money
    end
  end
end
