module FinchAPI
  module Models
    type paging = { offset: Integer, count: Integer }

    class Paging < FinchAPI::Internal::Type::BaseModel
      attr_accessor offset: Integer

      attr_reader count: Integer?

      def count=: (Integer) -> Integer

      def initialize: (offset: Integer, ?count: Integer) -> void

      def to_hash: -> { offset: Integer, count: Integer }
    end
  end
end
