module FinchAPI
  module Models
    type provider =
      {
        id: String,
        authentication_methods: ::Array[FinchAPI::Provider::AuthenticationMethod],
        beta: bool,
        display_name: String,
        icon: String,
        logo: String,
        manual: bool,
        mfa_required: bool,
        primary_color: String,
        products: ::Array[String]
      }

    class Provider < FinchAPI::Internal::Type::BaseModel
      attr_reader id: String?

      def id=: (String) -> String

      attr_reader authentication_methods: ::Array[FinchAPI::Provider::AuthenticationMethod]?

      def authentication_methods=: (
        ::Array[FinchAPI::Provider::AuthenticationMethod]
      ) -> ::Array[FinchAPI::Provider::AuthenticationMethod]

      attr_reader beta: bool?

      def beta=: (bool) -> bool

      attr_reader display_name: String?

      def display_name=: (String) -> String

      attr_reader icon: String?

      def icon=: (String) -> String

      attr_reader logo: String?

      def logo=: (String) -> String

      attr_reader manual: bool?

      def manual=: (bool) -> bool

      attr_reader mfa_required: bool?

      def mfa_required=: (bool) -> bool

      attr_reader primary_color: String?

      def primary_color=: (String) -> String

      attr_reader products: ::Array[String]?

      def products=: (::Array[String]) -> ::Array[String]

      def initialize: (
        ?id: String,
        ?authentication_methods: ::Array[FinchAPI::Provider::AuthenticationMethod],
        ?beta: bool,
        ?display_name: String,
        ?icon: String,
        ?logo: String,
        ?manual: bool,
        ?mfa_required: bool,
        ?primary_color: String,
        ?products: ::Array[String]
      ) -> void

      type authentication_method =
        {
          benefits_support: FinchAPI::HRIS::BenefitsSupport?,
          supported_fields: FinchAPI::Provider::AuthenticationMethod::SupportedFields?,
          type: FinchAPI::Provider::AuthenticationMethod::type_
        }

      class AuthenticationMethod < FinchAPI::Internal::Type::BaseModel
        attr_accessor benefits_support: FinchAPI::HRIS::BenefitsSupport?

        attr_accessor supported_fields: FinchAPI::Provider::AuthenticationMethod::SupportedFields?

        attr_reader type: FinchAPI::Provider::AuthenticationMethod::type_?

        def type=: (
          FinchAPI::Provider::AuthenticationMethod::type_
        ) -> FinchAPI::Provider::AuthenticationMethod::type_

        def initialize: (
          ?benefits_support: FinchAPI::HRIS::BenefitsSupport?,
          ?supported_fields: FinchAPI::Provider::AuthenticationMethod::SupportedFields?,
          ?type: FinchAPI::Provider::AuthenticationMethod::type_
        ) -> void

        type supported_fields =
          {
            company: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company,
            directory: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory,
            employment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment,
            individual: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual,
            pay_group: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayGroup,
            pay_statement: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement,
            payment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment
          }

        class SupportedFields < FinchAPI::Internal::Type::BaseModel
          attr_reader company: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company?

          def company=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company

          attr_reader directory: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory?

          def directory=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory

          attr_reader employment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment?

          def employment=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment

          attr_reader individual: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual?

          def individual=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual

          attr_reader pay_group: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayGroup?

          def pay_group=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayGroup
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayGroup

          attr_reader pay_statement: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement?

          def pay_statement=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement

          attr_reader payment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment?

          def payment=: (
            FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment
          ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment

          def initialize: (
            ?company: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company,
            ?directory: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory,
            ?employment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment,
            ?individual: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual,
            ?pay_group: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayGroup,
            ?pay_statement: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement,
            ?payment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment
          ) -> void

          type company =
            {
              id: bool,
              accounts: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Accounts,
              departments: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments,
              ein: bool,
              entity: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Entity,
              legal_name: bool,
              locations: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Locations,
              primary_email: bool,
              primary_phone_number: bool
            }

          class Company < FinchAPI::Internal::Type::BaseModel
            attr_reader id: bool?

            def id=: (bool) -> bool

            attr_reader accounts: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Accounts?

            def accounts=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Accounts
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Accounts

            attr_reader departments: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments?

            def departments=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments

            attr_reader ein: bool?

            def ein=: (bool) -> bool

            attr_reader entity: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Entity?

            def entity=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Entity
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Entity

            attr_reader legal_name: bool?

            def legal_name=: (bool) -> bool

            attr_reader locations: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Locations?

            def locations=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Locations
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Locations

            attr_reader primary_email: bool?

            def primary_email=: (bool) -> bool

            attr_reader primary_phone_number: bool?

            def primary_phone_number=: (bool) -> bool

            def initialize: (
              ?id: bool,
              ?accounts: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Accounts,
              ?departments: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments,
              ?ein: bool,
              ?entity: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Entity,
              ?legal_name: bool,
              ?locations: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Locations,
              ?primary_email: bool,
              ?primary_phone_number: bool
            ) -> void

            type accounts =
              {
                account_name: bool,
                account_number: bool,
                account_type: bool,
                institution_name: bool,
                routing_number: bool
              }

            class Accounts < FinchAPI::Internal::Type::BaseModel
              attr_reader account_name: bool?

              def account_name=: (bool) -> bool

              attr_reader account_number: bool?

              def account_number=: (bool) -> bool

              attr_reader account_type: bool?

              def account_type=: (bool) -> bool

              attr_reader institution_name: bool?

              def institution_name=: (bool) -> bool

              attr_reader routing_number: bool?

              def routing_number=: (bool) -> bool

              def initialize: (
                ?account_name: bool,
                ?account_number: bool,
                ?account_type: bool,
                ?institution_name: bool,
                ?routing_number: bool
              ) -> void
            end

            type departments =
              {
                name: bool,
                parent: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments::Parent
              }

            class Departments < FinchAPI::Internal::Type::BaseModel
              attr_reader name: bool?

              def name=: (bool) -> bool

              attr_reader parent: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments::Parent?

              def parent=: (
                FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments::Parent
              ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments::Parent

              def initialize: (
                ?name: bool,
                ?parent: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Company::Departments::Parent
              ) -> void

              type parent = { name: bool }

              class Parent < FinchAPI::Internal::Type::BaseModel
                attr_reader name: bool?

                def name=: (bool) -> bool

                def initialize: (?name: bool) -> void
              end
            end

            type entity = { subtype: bool, type: bool }

            class Entity < FinchAPI::Internal::Type::BaseModel
              attr_reader subtype: bool?

              def subtype=: (bool) -> bool

              attr_reader type: bool?

              def type=: (bool) -> bool

              def initialize: (?subtype: bool, ?type: bool) -> void
            end

            type locations =
              {
                city: bool,
                country: bool,
                :line1 => bool,
                :line2 => bool,
                postal_code: bool,
                state: bool
              }

            class Locations < FinchAPI::Internal::Type::BaseModel
              attr_reader city: bool?

              def city=: (bool) -> bool

              attr_reader country: bool?

              def country=: (bool) -> bool

              attr_reader line1: bool?

              def line1=: (bool) -> bool

              attr_reader line2: bool?

              def line2=: (bool) -> bool

              attr_reader postal_code: bool?

              def postal_code=: (bool) -> bool

              attr_reader state: bool?

              def state=: (bool) -> bool

              def initialize: (
                ?city: bool,
                ?country: bool,
                ?line1: bool,
                ?line2: bool,
                ?postal_code: bool,
                ?state: bool
              ) -> void
            end
          end

          type directory =
            {
              individuals: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals,
              paging: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Paging
            }

          class Directory < FinchAPI::Internal::Type::BaseModel
            attr_reader individuals: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals?

            def individuals=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals

            attr_reader paging: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Paging?

            def paging=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Paging
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Paging

            def initialize: (
              ?individuals: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals,
              ?paging: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Paging
            ) -> void

            type individuals =
              {
                id: bool,
                department: bool,
                first_name: bool,
                is_active: bool,
                last_name: bool,
                manager: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals::Manager,
                middle_name: bool
              }

            class Individuals < FinchAPI::Internal::Type::BaseModel
              attr_reader id: bool?

              def id=: (bool) -> bool

              attr_reader department: bool?

              def department=: (bool) -> bool

              attr_reader first_name: bool?

              def first_name=: (bool) -> bool

              attr_reader is_active: bool?

              def is_active=: (bool) -> bool

              attr_reader last_name: bool?

              def last_name=: (bool) -> bool

              attr_reader manager: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals::Manager?

              def manager=: (
                FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals::Manager
              ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals::Manager

              attr_reader middle_name: bool?

              def middle_name=: (bool) -> bool

              def initialize: (
                ?id: bool,
                ?department: bool,
                ?first_name: bool,
                ?is_active: bool,
                ?last_name: bool,
                ?manager: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Directory::Individuals::Manager,
                ?middle_name: bool
              ) -> void

              type manager = { id: bool }

              class Manager < FinchAPI::Internal::Type::BaseModel
                attr_reader id: bool?

                def id=: (bool) -> bool

                def initialize: (?id: bool) -> void
              end
            end

            type paging = { count: bool, offset: bool }

            class Paging < FinchAPI::Internal::Type::BaseModel
              attr_reader count: bool?

              def count=: (bool) -> bool

              attr_reader offset: bool?

              def offset=: (bool) -> bool

              def initialize: (?count: bool, ?offset: bool) -> void
            end
          end

          type employment =
            {
              id: bool,
              class_code: bool,
              custom_fields: bool,
              department: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Department,
              employment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Employment,
              employment_status: bool,
              end_date: bool,
              first_name: bool,
              income: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Income,
              income_history: bool,
              is_active: bool,
              last_name: bool,
              location: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Location,
              manager: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Manager,
              middle_name: bool,
              start_date: bool,
              title: bool
            }

          class Employment < FinchAPI::Internal::Type::BaseModel
            attr_reader id: bool?

            def id=: (bool) -> bool

            attr_reader class_code: bool?

            def class_code=: (bool) -> bool

            attr_reader custom_fields: bool?

            def custom_fields=: (bool) -> bool

            attr_reader department: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Department?

            def department=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Department
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Department

            attr_reader employment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Employment?

            def employment=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Employment
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Employment

            attr_reader employment_status: bool?

            def employment_status=: (bool) -> bool

            attr_reader end_date: bool?

            def end_date=: (bool) -> bool

            attr_reader first_name: bool?

            def first_name=: (bool) -> bool

            attr_reader income: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Income?

            def income=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Income
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Income

            attr_reader income_history: bool?

            def income_history=: (bool) -> bool

            attr_reader is_active: bool?

            def is_active=: (bool) -> bool

            attr_reader last_name: bool?

            def last_name=: (bool) -> bool

            attr_reader location: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Location?

            def location=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Location
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Location

            attr_reader manager: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Manager?

            def manager=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Manager
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Manager

            attr_reader middle_name: bool?

            def middle_name=: (bool) -> bool

            attr_reader start_date: bool?

            def start_date=: (bool) -> bool

            attr_reader title: bool?

            def title=: (bool) -> bool

            def initialize: (
              ?id: bool,
              ?class_code: bool,
              ?custom_fields: bool,
              ?department: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Department,
              ?employment: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Employment,
              ?employment_status: bool,
              ?end_date: bool,
              ?first_name: bool,
              ?income: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Income,
              ?income_history: bool,
              ?is_active: bool,
              ?last_name: bool,
              ?location: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Location,
              ?manager: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Employment::Manager,
              ?middle_name: bool,
              ?start_date: bool,
              ?title: bool
            ) -> void

            type department = { name: bool }

            class Department < FinchAPI::Internal::Type::BaseModel
              attr_reader name: bool?

              def name=: (bool) -> bool

              def initialize: (?name: bool) -> void
            end

            type employment = { subtype: bool, type: bool }

            class Employment < FinchAPI::Internal::Type::BaseModel
              attr_reader subtype: bool?

              def subtype=: (bool) -> bool

              attr_reader type: bool?

              def type=: (bool) -> bool

              def initialize: (?subtype: bool, ?type: bool) -> void
            end

            type income = { amount: bool, currency: bool, unit: bool }

            class Income < FinchAPI::Internal::Type::BaseModel
              attr_reader amount: bool?

              def amount=: (bool) -> bool

              attr_reader currency: bool?

              def currency=: (bool) -> bool

              attr_reader unit: bool?

              def unit=: (bool) -> bool

              def initialize: (
                ?amount: bool,
                ?currency: bool,
                ?unit: bool
              ) -> void
            end

            type location =
              {
                city: bool,
                country: bool,
                :line1 => bool,
                :line2 => bool,
                postal_code: bool,
                state: bool
              }

            class Location < FinchAPI::Internal::Type::BaseModel
              attr_reader city: bool?

              def city=: (bool) -> bool

              attr_reader country: bool?

              def country=: (bool) -> bool

              attr_reader line1: bool?

              def line1=: (bool) -> bool

              attr_reader line2: bool?

              def line2=: (bool) -> bool

              attr_reader postal_code: bool?

              def postal_code=: (bool) -> bool

              attr_reader state: bool?

              def state=: (bool) -> bool

              def initialize: (
                ?city: bool,
                ?country: bool,
                ?line1: bool,
                ?line2: bool,
                ?postal_code: bool,
                ?state: bool
              ) -> void
            end

            type manager = { id: bool }

            class Manager < FinchAPI::Internal::Type::BaseModel
              attr_reader id: bool?

              def id=: (bool) -> bool

              def initialize: (?id: bool) -> void
            end
          end

          type individual =
            {
              id: bool,
              dob: bool,
              emails: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Emails,
              encrypted_ssn: bool,
              ethnicity: bool,
              first_name: bool,
              gender: bool,
              last_name: bool,
              middle_name: bool,
              phone_numbers: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::PhoneNumbers,
              preferred_name: bool,
              residence: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Residence,
              ssn: bool
            }

          class Individual < FinchAPI::Internal::Type::BaseModel
            attr_reader id: bool?

            def id=: (bool) -> bool

            attr_reader dob: bool?

            def dob=: (bool) -> bool

            attr_reader emails: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Emails?

            def emails=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Emails
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Emails

            attr_reader encrypted_ssn: bool?

            def encrypted_ssn=: (bool) -> bool

            attr_reader ethnicity: bool?

            def ethnicity=: (bool) -> bool

            attr_reader first_name: bool?

            def first_name=: (bool) -> bool

            attr_reader gender: bool?

            def gender=: (bool) -> bool

            attr_reader last_name: bool?

            def last_name=: (bool) -> bool

            attr_reader middle_name: bool?

            def middle_name=: (bool) -> bool

            attr_reader phone_numbers: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::PhoneNumbers?

            def phone_numbers=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::PhoneNumbers
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::PhoneNumbers

            attr_reader preferred_name: bool?

            def preferred_name=: (bool) -> bool

            attr_reader residence: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Residence?

            def residence=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Residence
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Residence

            attr_reader ssn: bool?

            def ssn=: (bool) -> bool

            def initialize: (
              ?id: bool,
              ?dob: bool,
              ?emails: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Emails,
              ?encrypted_ssn: bool,
              ?ethnicity: bool,
              ?first_name: bool,
              ?gender: bool,
              ?last_name: bool,
              ?middle_name: bool,
              ?phone_numbers: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::PhoneNumbers,
              ?preferred_name: bool,
              ?residence: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Individual::Residence,
              ?ssn: bool
            ) -> void

            type emails = { data: bool, type: bool }

            class Emails < FinchAPI::Internal::Type::BaseModel
              attr_reader data: bool?

              def data=: (bool) -> bool

              attr_reader type: bool?

              def type=: (bool) -> bool

              def initialize: (?data: bool, ?type: bool) -> void
            end

            type phone_numbers = { data: bool, type: bool }

            class PhoneNumbers < FinchAPI::Internal::Type::BaseModel
              attr_reader data: bool?

              def data=: (bool) -> bool

              attr_reader type: bool?

              def type=: (bool) -> bool

              def initialize: (?data: bool, ?type: bool) -> void
            end

            type residence =
              {
                city: bool,
                country: bool,
                :line1 => bool,
                :line2 => bool,
                postal_code: bool,
                state: bool
              }

            class Residence < FinchAPI::Internal::Type::BaseModel
              attr_reader city: bool?

              def city=: (bool) -> bool

              attr_reader country: bool?

              def country=: (bool) -> bool

              attr_reader line1: bool?

              def line1=: (bool) -> bool

              attr_reader line2: bool?

              def line2=: (bool) -> bool

              attr_reader postal_code: bool?

              def postal_code=: (bool) -> bool

              attr_reader state: bool?

              def state=: (bool) -> bool

              def initialize: (
                ?city: bool,
                ?country: bool,
                ?line1: bool,
                ?line2: bool,
                ?postal_code: bool,
                ?state: bool
              ) -> void
            end
          end

          type pay_group =
            {
              id: bool,
              individual_ids: bool,
              name: bool,
              pay_frequencies: bool
            }

          class PayGroup < FinchAPI::Internal::Type::BaseModel
            attr_reader id: bool?

            def id=: (bool) -> bool

            attr_reader individual_ids: bool?

            def individual_ids=: (bool) -> bool

            attr_reader name: bool?

            def name=: (bool) -> bool

            attr_reader pay_frequencies: bool?

            def pay_frequencies=: (bool) -> bool

            def initialize: (
              ?id: bool,
              ?individual_ids: bool,
              ?name: bool,
              ?pay_frequencies: bool
            ) -> void
          end

          type pay_statement =
            {
              paging: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::Paging,
              pay_statements: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements
            }

          class PayStatement < FinchAPI::Internal::Type::BaseModel
            attr_reader paging: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::Paging?

            def paging=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::Paging
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::Paging

            attr_reader pay_statements: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements?

            def pay_statements=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements

            def initialize: (
              ?paging: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::Paging,
              ?pay_statements: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements
            ) -> void

            type paging = { count: bool, offset: bool }

            class Paging < FinchAPI::Internal::Type::BaseModel
              attr_accessor count: bool

              attr_accessor offset: bool

              def initialize: (count: bool, offset: bool) -> void
            end

            type pay_statements =
              {
                earnings: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Earnings,
                employee_deductions: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployeeDeductions,
                employer_contributions: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployerContributions,
                gross_pay: bool,
                individual_id: bool,
                net_pay: bool,
                payment_method: bool,
                taxes: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Taxes,
                total_hours: bool,
                type: bool
              }

            class PayStatements < FinchAPI::Internal::Type::BaseModel
              attr_reader earnings: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Earnings?

              def earnings=: (
                FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Earnings
              ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Earnings

              attr_reader employee_deductions: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployeeDeductions?

              def employee_deductions=: (
                FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployeeDeductions
              ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployeeDeductions

              attr_reader employer_contributions: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployerContributions?

              def employer_contributions=: (
                FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployerContributions
              ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployerContributions

              attr_reader gross_pay: bool?

              def gross_pay=: (bool) -> bool

              attr_reader individual_id: bool?

              def individual_id=: (bool) -> bool

              attr_reader net_pay: bool?

              def net_pay=: (bool) -> bool

              attr_reader payment_method: bool?

              def payment_method=: (bool) -> bool

              attr_reader taxes: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Taxes?

              def taxes=: (
                FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Taxes
              ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Taxes

              attr_reader total_hours: bool?

              def total_hours=: (bool) -> bool

              attr_reader type: bool?

              def type=: (bool) -> bool

              def initialize: (
                ?earnings: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Earnings,
                ?employee_deductions: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployeeDeductions,
                ?employer_contributions: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::EmployerContributions,
                ?gross_pay: bool,
                ?individual_id: bool,
                ?net_pay: bool,
                ?payment_method: bool,
                ?taxes: FinchAPI::Provider::AuthenticationMethod::SupportedFields::PayStatement::PayStatements::Taxes,
                ?total_hours: bool,
                ?type: bool
              ) -> void

              type earnings =
                { amount: bool, currency: bool, name: bool, type: bool }

              class Earnings < FinchAPI::Internal::Type::BaseModel
                attr_reader amount: bool?

                def amount=: (bool) -> bool

                attr_reader currency: bool?

                def currency=: (bool) -> bool

                attr_reader name: bool?

                def name=: (bool) -> bool

                attr_reader type: bool?

                def type=: (bool) -> bool

                def initialize: (
                  ?amount: bool,
                  ?currency: bool,
                  ?name: bool,
                  ?type: bool
                ) -> void
              end

              type employee_deductions =
                {
                  amount: bool,
                  currency: bool,
                  name: bool,
                  pre_tax: bool,
                  type: bool
                }

              class EmployeeDeductions < FinchAPI::Internal::Type::BaseModel
                attr_reader amount: bool?

                def amount=: (bool) -> bool

                attr_reader currency: bool?

                def currency=: (bool) -> bool

                attr_reader name: bool?

                def name=: (bool) -> bool

                attr_reader pre_tax: bool?

                def pre_tax=: (bool) -> bool

                attr_reader type: bool?

                def type=: (bool) -> bool

                def initialize: (
                  ?amount: bool,
                  ?currency: bool,
                  ?name: bool,
                  ?pre_tax: bool,
                  ?type: bool
                ) -> void
              end

              type employer_contributions =
                { amount: bool, currency: bool, name: bool }

              class EmployerContributions < FinchAPI::Internal::Type::BaseModel
                attr_reader amount: bool?

                def amount=: (bool) -> bool

                attr_reader currency: bool?

                def currency=: (bool) -> bool

                attr_reader name: bool?

                def name=: (bool) -> bool

                def initialize: (
                  ?amount: bool,
                  ?currency: bool,
                  ?name: bool
                ) -> void
              end

              type taxes =
                {
                  amount: bool,
                  currency: bool,
                  employer: bool,
                  name: bool,
                  type: bool
                }

              class Taxes < FinchAPI::Internal::Type::BaseModel
                attr_reader amount: bool?

                def amount=: (bool) -> bool

                attr_reader currency: bool?

                def currency=: (bool) -> bool

                attr_reader employer: bool?

                def employer=: (bool) -> bool

                attr_reader name: bool?

                def name=: (bool) -> bool

                attr_reader type: bool?

                def type=: (bool) -> bool

                def initialize: (
                  ?amount: bool,
                  ?currency: bool,
                  ?employer: bool,
                  ?name: bool,
                  ?type: bool
                ) -> void
              end
            end
          end

          type payment =
            {
              id: bool,
              company_debit: bool,
              debit_date: bool,
              employee_taxes: bool,
              employer_taxes: bool,
              gross_pay: bool,
              individual_ids: bool,
              net_pay: bool,
              pay_date: bool,
              pay_frequencies: bool,
              pay_group_ids: bool,
              pay_period: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment::PayPeriod
            }

          class Payment < FinchAPI::Internal::Type::BaseModel
            attr_reader id: bool?

            def id=: (bool) -> bool

            attr_reader company_debit: bool?

            def company_debit=: (bool) -> bool

            attr_reader debit_date: bool?

            def debit_date=: (bool) -> bool

            attr_reader employee_taxes: bool?

            def employee_taxes=: (bool) -> bool

            attr_reader employer_taxes: bool?

            def employer_taxes=: (bool) -> bool

            attr_reader gross_pay: bool?

            def gross_pay=: (bool) -> bool

            attr_reader individual_ids: bool?

            def individual_ids=: (bool) -> bool

            attr_reader net_pay: bool?

            def net_pay=: (bool) -> bool

            attr_reader pay_date: bool?

            def pay_date=: (bool) -> bool

            attr_reader pay_frequencies: bool?

            def pay_frequencies=: (bool) -> bool

            attr_reader pay_group_ids: bool?

            def pay_group_ids=: (bool) -> bool

            attr_reader pay_period: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment::PayPeriod?

            def pay_period=: (
              FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment::PayPeriod
            ) -> FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment::PayPeriod

            def initialize: (
              ?id: bool,
              ?company_debit: bool,
              ?debit_date: bool,
              ?employee_taxes: bool,
              ?employer_taxes: bool,
              ?gross_pay: bool,
              ?individual_ids: bool,
              ?net_pay: bool,
              ?pay_date: bool,
              ?pay_frequencies: bool,
              ?pay_group_ids: bool,
              ?pay_period: FinchAPI::Provider::AuthenticationMethod::SupportedFields::Payment::PayPeriod
            ) -> void

            type pay_period = { end_date: bool, start_date: bool }

            class PayPeriod < FinchAPI::Internal::Type::BaseModel
              attr_reader end_date: bool?

              def end_date=: (bool) -> bool

              attr_reader start_date: bool?

              def start_date=: (bool) -> bool

              def initialize: (?end_date: bool, ?start_date: bool) -> void
            end
          end
        end

        type type_ =
          :assisted | :credential | :api_token | :api_credential | :oauth

        module Type
          extend FinchAPI::Internal::Type::Enum

          ASSISTED: :assisted
          CREDENTIAL: :credential
          API_TOKEN: :api_token
          API_CREDENTIAL: :api_credential
          OAUTH: :oauth

          def self?.values: -> ::Array[FinchAPI::Provider::AuthenticationMethod::type_]
        end
      end
    end
  end
end
