module FinchAPI
  module Models
    type provider_list_params =
      {  } & FinchAPI::Internal::Type::request_parameters

    class ProviderListParams < FinchAPI::BaseModel
      extend FinchAPI::Internal::Type::RequestParameters::Converter
      include FinchAPI::Internal::Type::RequestParameters

      def initialize: (?request_options: FinchAPI::request_opts) -> void

      def to_hash: -> FinchAPI::Models::provider_list_params
    end
  end
end
