module FinchAPI
  module Models
    type webhook_event =
      FinchAPI::AccountUpdateEvent
      | FinchAPI::CompanyEvent
      | FinchAPI::JobCompletionEvent
      | FinchAPI::DirectoryEvent
      | FinchAPI::EmploymentEvent
      | FinchAPI::IndividualEvent
      | FinchAPI::PaymentEvent
      | FinchAPI::PayStatementEvent

    module WebhookEvent
      extend FinchAPI::Internal::Type::Union

      def self?.variants: -> ::Array[FinchAPI::Models::webhook_event]
    end
  end
end
