module FinchAPI
  module Resources
    class Connect
      class Sessions
        def new: (
          customer_email: String?,
          customer_id: String,
          customer_name: String,
          integration: FinchAPI::Connect::SessionNewParams::Integration?,
          manual: bool?,
          minutes_to_expire: Float?,
          products: ::Array[FinchAPI::Models::Connect::SessionNewParams::product],
          redirect_uri: String?,
          sandbox: FinchAPI::Models::Connect::SessionNewParams::sandbox?,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Connect::SessionNewResponse

        def reauthenticate: (
          connection_id: String,
          minutes_to_expire: Integer,
          products: ::Array[FinchAPI::Models::Connect::SessionReauthenticateParams::product]?,
          redirect_uri: String?,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::Connect::SessionReauthenticateResponse

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
