module FinchAPI
  module Resources
    class HRIS
      class Benefits
        attr_reader individuals: FinchAPI::Resources::HRIS::Benefits::Individuals

        def create: (
          ?company_contribution: FinchAPI::Models::HRIS::BenefitCreateParams::CompanyContribution?,
          ?description: String,
          ?frequency: FinchAPI::Models::HRIS::benefit_frequency?,
          ?type: FinchAPI::Models::HRIS::benefit_type?,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::HRIS::CreateCompanyBenefitsResponse

        def retrieve: (
          String benefit_id,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::HRIS::CompanyBenefit

        def update: (
          String benefit_id,
          ?description: String,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Models::HRIS::UpdateCompanyBenefitResponse

        def list: (
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Internal::SinglePage[FinchAPI::Models::HRIS::CompanyBenefit]

        def list_supported_benefits: (
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Internal::SinglePage[FinchAPI::Models::HRIS::BenefitListSupportedBenefitsResponse]

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
