module FinchAPI
  module Resources
    class HRIS
      class Company
        def retrieve: (
          ?entity_ids: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::HRIS::HRISCompany

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
