module FinchAPI
  module Resources
    class HRIS
      class Company
        attr_reader pay_statement_item: FinchAPI::Resources::HRIS::Company::PayStatementItem

        def retrieve: (
          entity_ids: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::HRIS::HRISCompany

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
