module FinchAPI
  module Resources
    class HRIS
      class Employments
        def retrieve_many: (
          requests: ::Array[FinchAPI::HRIS::EmploymentRetrieveManyParams::Request],
          ?entity_ids: ::Array[String],
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Internal::ResponsesPage[FinchAPI::HRIS::EmploymentDataResponse]

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
