module FinchAPI
  module Resources
    class HRIS
      class Individuals
        def retrieve_many: (
          requests: ::Array[FinchAPI::HRIS::IndividualRetrieveManyParams::Request],
          ?entity_ids: ::Array[String],
          ?options: FinchAPI::HRIS::IndividualRetrieveManyParams::Options?,
          ?request_options: FinchAPI::request_opts
        ) -> FinchAPI::Internal::ResponsesPage[FinchAPI::HRIS::IndividualResponse]

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
