module FinchAPI
  module Resources
    class Sandbox
      class Connections
        attr_reader accounts: FinchAPI::Resources::Sandbox::Connections::Accounts

        def create:
          (
            FinchAPI::Models::Sandbox::ConnectionCreateParams
            | ::Hash[Symbol, top] params
          ) -> FinchAPI::Models::Sandbox::ConnectionCreateResponse
          | (
            provider_id: String,
            authentication_type: FinchAPI::Models::Sandbox::ConnectionCreateParams::authentication_type,
            employee_size: Integer,
            products: ::Array[String],
            request_options: FinchAPI::request_opts
          ) -> FinchAPI::Models::Sandbox::ConnectionCreateResponse

        def initialize: (client: FinchAPI::Client) -> void
      end
    end
  end
end
