module FinchAPI
  module Models
    module HRIS
      type benefit_list_params = {  } & FinchAPI::request_parameters

      class BenefitListParams < FinchAPI::BaseModel
        extend FinchAPI::RequestParameters::Converter
        include FinchAPI::RequestParameters

        def initialize: (?request_options: FinchAPI::request_opts) -> void

        def to_hash: -> FinchAPI::Models::HRIS::benefit_list_params
      end
    end
  end
end
