module FinchAPI
  module Models
    module HRIS
      type company_retrieve_params = {  } & FinchAPI::request_parameters

      class CompanyRetrieveParams < FinchAPI::BaseModel
        extend FinchAPI::RequestParameters::Converter
        include FinchAPI::RequestParameters

        def initialize:
          (request_options: FinchAPI::request_opts) -> void
          | (
            ?FinchAPI::Models::HRIS::company_retrieve_params
            | FinchAPI::BaseModel data
          ) -> void

        def to_hash: -> FinchAPI::Models::HRIS::company_retrieve_params
      end
    end
  end
end
