module FinchAPI
  module Models
    module HRIS
      type document_retreive_params = {  } & FinchAPI::request_parameters

      class DocumentRetreiveParams < FinchAPI::BaseModel
        extend FinchAPI::RequestParameters::Converter
        include FinchAPI::RequestParameters

        def initialize: (?request_options: FinchAPI::request_opts) -> void

        def to_hash: -> FinchAPI::Models::HRIS::document_retreive_params
      end
    end
  end
end
