module FinchAPI
  module Models
    module HRIS
      type employment_data_response =
        {
          body: FinchAPI::Models::HRIS::EmploymentData,
          code: Integer,
          individual_id: String
        }

      class EmploymentDataResponse < FinchAPI::BaseModel
        attr_reader body: FinchAPI::Models::HRIS::EmploymentData?

        def body=: (
          FinchAPI::Models::HRIS::EmploymentData
        ) -> FinchAPI::Models::HRIS::EmploymentData

        attr_reader code: Integer?

        def code=: (Integer) -> Integer

        attr_reader individual_id: String?

        def individual_id=: (String) -> String

        def initialize:
          (
            ?body: FinchAPI::Models::HRIS::EmploymentData,
            ?code: Integer,
            ?individual_id: String
          ) -> void
          | (
            ?FinchAPI::Models::HRIS::employment_data_response
            | FinchAPI::BaseModel data
          ) -> void

        def to_hash: -> FinchAPI::Models::HRIS::employment_data_response
      end
    end
  end
end
