module FinchAPI
  module Models
    module HRIS
      type individual_in_directory =
        {
          id: String,
          department: FinchAPI::Models::HRIS::IndividualInDirectory::Department?,
          first_name: String?,
          is_active: bool?,
          last_name: String?,
          manager: FinchAPI::Models::HRIS::IndividualInDirectory::Manager?,
          middle_name: String?
        }

      class IndividualInDirectory < FinchAPI::BaseModel
        attr_reader id: String?

        def id=: (String) -> String

        attr_accessor department: FinchAPI::Models::HRIS::IndividualInDirectory::Department?

        attr_accessor first_name: String?

        attr_accessor is_active: bool?

        attr_accessor last_name: String?

        attr_accessor manager: FinchAPI::Models::HRIS::IndividualInDirectory::Manager?

        attr_accessor middle_name: String?

        def initialize:
          (
            id: String,
            department: FinchAPI::Models::HRIS::IndividualInDirectory::Department?,
            first_name: String?,
            is_active: bool?,
            last_name: String?,
            manager: FinchAPI::Models::HRIS::IndividualInDirectory::Manager?,
            middle_name: String?
          ) -> void
          | (
            ?FinchAPI::Models::HRIS::individual_in_directory
            | FinchAPI::BaseModel data
          ) -> void

        def to_hash: -> FinchAPI::Models::HRIS::individual_in_directory

        type department = { name: String? }

        class Department < FinchAPI::BaseModel
          attr_accessor name: String?

          def initialize:
            (name: String?) -> void
            | (
              ?FinchAPI::Models::HRIS::IndividualInDirectory::department
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::HRIS::IndividualInDirectory::department
        end

        type manager = { id: String }

        class Manager < FinchAPI::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          def initialize:
            (id: String) -> void
            | (
              ?FinchAPI::Models::HRIS::IndividualInDirectory::manager
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::HRIS::IndividualInDirectory::manager
        end
      end
    end
  end
end
