module FinchAPI
  module Models
    module Connect
      type session_reauthenticate_response =
        { connect_url: String, session_id: String }

      class SessionReauthenticateResponse < FinchAPI::BaseModel
        attr_accessor connect_url: String

        attr_accessor session_id: String

        def initialize: (connect_url: String, session_id: String) -> void

        def to_hash: -> FinchAPI::Models::Connect::session_reauthenticate_response
      end
    end
  end
end
