module FinchAPI
  module Models
    module Connect
      type session_reauthenticate_params =
        {
          connection_id: String,
          minutes_to_expire: Integer,
          products: ::Array[FinchAPI::Models::Connect::SessionReauthenticateParams::product]?,
          redirect_uri: String?
        }
        & FinchAPI::Internal::Type::request_parameters

      class SessionReauthenticateParams < FinchAPI::Internal::Type::BaseModel
        extend FinchAPI::Internal::Type::RequestParameters::Converter
        include FinchAPI::Internal::Type::RequestParameters

        attr_accessor connection_id: String

        attr_reader minutes_to_expire: Integer?

        def minutes_to_expire=: (Integer) -> Integer

        attr_accessor products: ::Array[FinchAPI::Models::Connect::SessionReauthenticateParams::product]?

        attr_accessor redirect_uri: String?

        def initialize: (
          connection_id: String,
          ?minutes_to_expire: Integer,
          ?products: ::Array[FinchAPI::Models::Connect::SessionReauthenticateParams::product]?,
          ?redirect_uri: String?,
          ?request_options: FinchAPI::request_opts
        ) -> void

        def to_hash: -> {
          connection_id: String,
          minutes_to_expire: Integer,
          products: ::Array[FinchAPI::Models::Connect::SessionReauthenticateParams::product]?,
          redirect_uri: String?,
          request_options: FinchAPI::RequestOptions
        }

        type product =
          :benefits
          | :company
          | :deduction
          | :directory
          | :documents
          | :employment
          | :individual
          | :payment
          | :pay_statement
          | :ssn

        module Product
          extend FinchAPI::Internal::Type::Enum

          BENEFITS: :benefits
          COMPANY: :company
          DEDUCTION: :deduction
          DIRECTORY: :directory
          DOCUMENTS: :documents
          EMPLOYMENT: :employment
          INDIVIDUAL: :individual
          PAYMENT: :payment
          PAY_STATEMENT: :pay_statement
          SSN: :ssn

          def self?.values: -> ::Array[FinchAPI::Models::Connect::SessionReauthenticateParams::product]
        end
      end
    end
  end
end
