module FinchAPI
  module Resources
    class Account
      def disconnect: (
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::Models::DisconnectResponse

      def introspect: (
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::Models::Introspection

      def initialize: (client: FinchAPI::Client) -> void
    end
  end
end
