module FinchAPI
  module Resources
    class Providers
      def list: (
        ?request_options: FinchAPI::request_opts
      ) -> FinchAPI::SinglePage[FinchAPI::Models::Provider]

      def initialize: (client: FinchAPI::Client) -> void
    end
  end
end
