module FinchAPI
  module Models
    module Sandbox
      type employment_update_params =
        {
          class_code: String?,
          custom_fields: ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::CustomField],
          department: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Department?,
          employment: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment?,
          employment_status: FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment_status?,
          end_date: String?,
          first_name: String?,
          income: FinchAPI::Models::Income?,
          income_history: ::Array[FinchAPI::Models::Income?]?,
          is_active: bool?,
          last_name: String?,
          latest_rehire_date: String?,
          location: FinchAPI::Models::Location?,
          manager: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Manager?,
          middle_name: String?,
          source_id: String,
          start_date: String?,
          title: String?
        }
        & FinchAPI::request_parameters

      class EmploymentUpdateParams < FinchAPI::BaseModel
        extend FinchAPI::RequestParameters::Converter
        include FinchAPI::RequestParameters

        attr_accessor class_code: String?

        attr_reader custom_fields: ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::CustomField]?

        def custom_fields=: (
          ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::CustomField]
        ) -> ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::CustomField]

        attr_accessor department: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Department?

        attr_accessor employment: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment?

        attr_accessor employment_status: FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment_status?

        attr_accessor end_date: String?

        attr_accessor first_name: String?

        attr_accessor income: FinchAPI::Models::Income?

        attr_accessor income_history: ::Array[FinchAPI::Models::Income?]?

        attr_accessor is_active: bool?

        attr_accessor last_name: String?

        attr_accessor latest_rehire_date: String?

        attr_accessor location: FinchAPI::Models::Location?

        attr_accessor manager: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Manager?

        attr_accessor middle_name: String?

        attr_reader source_id: String?

        def source_id=: (String) -> String

        attr_accessor start_date: String?

        attr_accessor title: String?

        def initialize:
          (
            class_code: String?,
            custom_fields: ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::CustomField],
            department: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Department?,
            employment: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment?,
            employment_status: FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment_status?,
            end_date: String?,
            first_name: String?,
            income: FinchAPI::Models::Income?,
            income_history: ::Array[FinchAPI::Models::Income?]?,
            is_active: bool?,
            last_name: String?,
            latest_rehire_date: String?,
            location: FinchAPI::Models::Location?,
            manager: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Manager?,
            middle_name: String?,
            source_id: String,
            start_date: String?,
            title: String?,
            request_options: FinchAPI::request_opts
          ) -> void
          | (
            ?FinchAPI::Models::Sandbox::employment_update_params
            | FinchAPI::BaseModel data
          ) -> void

        def to_hash: -> FinchAPI::Models::Sandbox::employment_update_params

        type custom_field = { name: String?, value: top }

        class CustomField < FinchAPI::BaseModel
          attr_accessor name: String?

          attr_reader value: top?

          def value=: (top) -> top

          def initialize:
            (name: String?, value: top) -> void
            | (
              ?FinchAPI::Models::Sandbox::EmploymentUpdateParams::custom_field
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::Sandbox::EmploymentUpdateParams::custom_field
        end

        type department = { name: String? }

        class Department < FinchAPI::BaseModel
          attr_accessor name: String?

          def initialize:
            (name: String?) -> void
            | (
              ?FinchAPI::Models::Sandbox::EmploymentUpdateParams::department
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::Sandbox::EmploymentUpdateParams::department
        end

        type employment =
          {
            subtype: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::subtype?,
            type: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::type_?
          }

        class Employment < FinchAPI::BaseModel
          attr_accessor subtype: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::subtype?

          attr_accessor type: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::type_?

          def initialize:
            (
              subtype: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::subtype?,
              type: FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::type_?
            ) -> void
            | (
              ?FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment

          type subtype =
            :full_time
            | :intern
            | :part_time
            | :temp
            | :seasonal
            | :individual_contractor

          class Subtype < FinchAPI::Enum
            FULL_TIME: :full_time
            INTERN: :intern
            PART_TIME: :part_time
            TEMP: :temp
            SEASONAL: :seasonal
            INDIVIDUAL_CONTRACTOR: :individual_contractor

            def self.values: -> ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::subtype]
          end

          type type_ = :employee | :contractor

          class Type < FinchAPI::Enum
            EMPLOYEE: :employee
            CONTRACTOR: :contractor

            def self.values: -> ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::Employment::type_]
          end
        end

        type employment_status =
          :active
          | :deceased
          | :leave
          | :onboarding
          | :prehire
          | :retired
          | :terminated

        class EmploymentStatus < FinchAPI::Enum
          ACTIVE: :active
          DECEASED: :deceased
          LEAVE: :leave
          ONBOARDING: :onboarding
          PREHIRE: :prehire
          RETIRED: :retired
          TERMINATED: :terminated

          def self.values: -> ::Array[FinchAPI::Models::Sandbox::EmploymentUpdateParams::employment_status]
        end

        type manager = { id: String }

        class Manager < FinchAPI::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          def initialize:
            (id: String) -> void
            | (
              ?FinchAPI::Models::Sandbox::EmploymentUpdateParams::manager
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::Sandbox::EmploymentUpdateParams::manager
        end
      end
    end
  end
end
