module FinchAPI
  module Internal
    class Page[Elem]
      include FinchAPI::Internal::Type::BasePage[Elem]

      attr_accessor data: ::Array[Elem]?

      attr_accessor paging: FinchAPI::Paging

      def inspect: -> String
    end
  end
end
