module FinchAPI
  module Models
    module Sandbox
      module Connections
        type account_update_params =
          { connection_status: FinchAPI::Models::connection_status_type }
          & FinchAPI::request_parameters

        class AccountUpdateParams < FinchAPI::BaseModel
          extend FinchAPI::RequestParameters::Converter
          include FinchAPI::RequestParameters

          attr_reader connection_status: FinchAPI::Models::connection_status_type?

          def connection_status=: (
            FinchAPI::Models::connection_status_type
          ) -> FinchAPI::Models::connection_status_type

          def initialize:
            (
              ?connection_status: FinchAPI::Models::connection_status_type,
              ?request_options: FinchAPI::request_opts
            ) -> void
            | (
              ?FinchAPI::Models::Sandbox::Connections::account_update_params
              | FinchAPI::BaseModel data
            ) -> void

          def to_hash: -> FinchAPI::Models::Sandbox::Connections::account_update_params
        end
      end
    end
  end
end
